// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TCsP.proto

#include "TCsP.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR TCsP_IndexPair::TCsP_IndexPair(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.latindex_)*/0
  , /*decltype(_impl_.lonindex_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TCsP_IndexPairDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsP_IndexPairDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsP_IndexPairDefaultTypeInternal() {}
  union {
    TCsP_IndexPair _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsP_IndexPairDefaultTypeInternal _TCsP_IndexPair_default_instance_;
PROTOBUF_CONSTEXPR TCsP_LatLonPair::TCsP_LatLonPair(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.lat_)*/0
  , /*decltype(_impl_.lon_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TCsP_LatLonPairDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsP_LatLonPairDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsP_LatLonPairDefaultTypeInternal() {}
  union {
    TCsP_LatLonPair _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsP_LatLonPairDefaultTypeInternal _TCsP_LatLonPair_default_instance_;
PROTOBUF_CONSTEXPR TCsP_VorCellsIndex::TCsP_VorCellsIndex(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.vorcellsindex_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TCsP_VorCellsIndexDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsP_VorCellsIndexDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsP_VorCellsIndexDefaultTypeInternal() {}
  union {
    TCsP_VorCellsIndex _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsP_VorCellsIndexDefaultTypeInternal _TCsP_VorCellsIndex_default_instance_;
PROTOBUF_CONSTEXPR TCsP_Typhoon::TCsP_Typhoon(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.maxvorcells_)*/{}
  , /*decltype(_impl_.geocenters_)*/{}
  , /*decltype(_impl_.vorscellsindex_)*/{}
  , /*decltype(_impl_.starttimeindex_)*/0
  , /*decltype(_impl_.endtimeindex_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TCsP_TyphoonDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsP_TyphoonDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsP_TyphoonDefaultTypeInternal() {}
  union {
    TCsP_Typhoon _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsP_TyphoonDefaultTypeInternal _TCsP_Typhoon_default_instance_;
PROTOBUF_CONSTEXPR TCsP::TCsP(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.typhoons_)*/{}
  , /*decltype(_impl_.lats_)*/{}
  , /*decltype(_impl_.lons_)*/{}
  , /*decltype(_impl_.timeunits_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.time_noleap_)*/false
  , /*decltype(_impl_.firsttimevalue_)*/0
  , /*decltype(_impl_.timehourinterval_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TCsPDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsPDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsPDefaultTypeInternal() {}
  union {
    TCsP _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsPDefaultTypeInternal _TCsP_default_instance_;
static ::_pb::Metadata file_level_metadata_TCsP_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_TCsP_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_TCsP_2eproto = nullptr;

const uint32_t TableStruct_TCsP_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TCsP_IndexPair, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TCsP_IndexPair, _impl_.latindex_),
  PROTOBUF_FIELD_OFFSET(::TCsP_IndexPair, _impl_.lonindex_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TCsP_LatLonPair, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TCsP_LatLonPair, _impl_.lat_),
  PROTOBUF_FIELD_OFFSET(::TCsP_LatLonPair, _impl_.lon_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TCsP_VorCellsIndex, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TCsP_VorCellsIndex, _impl_.vorcellsindex_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.maxvorcells_),
  PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.geocenters_),
  PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.starttimeindex_),
  PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.endtimeindex_),
  PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.vorscellsindex_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TCsP, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.typhoons_),
  PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.timeunits_),
  PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.time_noleap_),
  PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.firsttimevalue_),
  PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.timehourinterval_),
  PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.lats_),
  PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.lons_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::TCsP_IndexPair)},
  { 8, -1, -1, sizeof(::TCsP_LatLonPair)},
  { 16, -1, -1, sizeof(::TCsP_VorCellsIndex)},
  { 23, -1, -1, sizeof(::TCsP_Typhoon)},
  { 34, -1, -1, sizeof(::TCsP)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_TCsP_IndexPair_default_instance_._instance,
  &::_TCsP_LatLonPair_default_instance_._instance,
  &::_TCsP_VorCellsIndex_default_instance_._instance,
  &::_TCsP_Typhoon_default_instance_._instance,
  &::_TCsP_default_instance_._instance,
};

const char descriptor_table_protodef_TCsP_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nTCsP.proto\"\342\003\n\004TCsP\022\037\n\010typhoons\030\001 \003(\0132"
  "\r.TCsP.Typhoon\022\021\n\ttimeUnits\030\002 \001(\t\022\023\n\013tim"
  "e_noleap\030\003 \001(\010\022\026\n\016firstTimeValue\030\004 \001(\005\022\030"
  "\n\020timeHourInterval\030\005 \001(\005\022\014\n\004lats\030\006 \003(\002\022\014"
  "\n\004lons\030\007 \003(\002\032/\n\tIndexPair\022\020\n\010latIndex\030\001 "
  "\001(\005\022\020\n\010lonIndex\030\002 \001(\005\032&\n\nLatLonPair\022\013\n\003l"
  "at\030\001 \001(\002\022\013\n\003lon\030\002 \001(\002\0327\n\rVorCellsIndex\022&"
  "\n\rvorCellsIndex\030\001 \003(\0132\017.TCsP.IndexPair\032\260"
  "\001\n\007Typhoon\022$\n\013maxVorCells\030\001 \003(\0132\017.TCsP.I"
  "ndexPair\022$\n\ngeoCenters\030\002 \003(\0132\020.TCsP.LatL"
  "onPair\022\026\n\016startTimeIndex\030\003 \001(\005\022\024\n\014endTim"
  "eIndex\030\004 \001(\005\022+\n\016vorsCellsIndex\030\005 \003(\0132\023.T"
  "CsP.VorCellsIndexb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_TCsP_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_TCsP_2eproto = {
    false, false, 505, descriptor_table_protodef_TCsP_2eproto,
    "TCsP.proto",
    &descriptor_table_TCsP_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_TCsP_2eproto::offsets,
    file_level_metadata_TCsP_2eproto, file_level_enum_descriptors_TCsP_2eproto,
    file_level_service_descriptors_TCsP_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_TCsP_2eproto_getter() {
  return &descriptor_table_TCsP_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_TCsP_2eproto(&descriptor_table_TCsP_2eproto);

// ===================================================================

class TCsP_IndexPair::_Internal {
 public:
};

TCsP_IndexPair::TCsP_IndexPair(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TCsP.IndexPair)
}
TCsP_IndexPair::TCsP_IndexPair(const TCsP_IndexPair& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TCsP_IndexPair* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.latindex_){}
    , decltype(_impl_.lonindex_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.latindex_, &from._impl_.latindex_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.lonindex_) -
    reinterpret_cast<char*>(&_impl_.latindex_)) + sizeof(_impl_.lonindex_));
  // @@protoc_insertion_point(copy_constructor:TCsP.IndexPair)
}

inline void TCsP_IndexPair::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.latindex_){0}
    , decltype(_impl_.lonindex_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TCsP_IndexPair::~TCsP_IndexPair() {
  // @@protoc_insertion_point(destructor:TCsP.IndexPair)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TCsP_IndexPair::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TCsP_IndexPair::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TCsP_IndexPair::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP.IndexPair)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.latindex_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.lonindex_) -
      reinterpret_cast<char*>(&_impl_.latindex_)) + sizeof(_impl_.lonindex_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TCsP_IndexPair::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 latIndex = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.latindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 lonIndex = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.lonindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TCsP_IndexPair::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TCsP.IndexPair)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 latIndex = 1;
  if (this->_internal_latindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_latindex(), target);
  }

  // int32 lonIndex = 2;
  if (this->_internal_lonindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_lonindex(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP.IndexPair)
  return target;
}

size_t TCsP_IndexPair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TCsP.IndexPair)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 latIndex = 1;
  if (this->_internal_latindex() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_latindex());
  }

  // int32 lonIndex = 2;
  if (this->_internal_lonindex() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_lonindex());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TCsP_IndexPair::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TCsP_IndexPair::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TCsP_IndexPair::GetClassData() const { return &_class_data_; }


void TCsP_IndexPair::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TCsP_IndexPair*>(&to_msg);
  auto& from = static_cast<const TCsP_IndexPair&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP.IndexPair)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_latindex() != 0) {
    _this->_internal_set_latindex(from._internal_latindex());
  }
  if (from._internal_lonindex() != 0) {
    _this->_internal_set_lonindex(from._internal_lonindex());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TCsP_IndexPair::CopyFrom(const TCsP_IndexPair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TCsP.IndexPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TCsP_IndexPair::IsInitialized() const {
  return true;
}

void TCsP_IndexPair::InternalSwap(TCsP_IndexPair* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_.lonindex_)
      + sizeof(TCsP_IndexPair::_impl_.lonindex_)
      - PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_.latindex_)>(
          reinterpret_cast<char*>(&_impl_.latindex_),
          reinterpret_cast<char*>(&other->_impl_.latindex_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TCsP_IndexPair::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TCsP_2eproto_getter, &descriptor_table_TCsP_2eproto_once,
      file_level_metadata_TCsP_2eproto[0]);
}

// ===================================================================

class TCsP_LatLonPair::_Internal {
 public:
};

TCsP_LatLonPair::TCsP_LatLonPair(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TCsP.LatLonPair)
}
TCsP_LatLonPair::TCsP_LatLonPair(const TCsP_LatLonPair& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TCsP_LatLonPair* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.lat_){}
    , decltype(_impl_.lon_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.lat_, &from._impl_.lat_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.lon_) -
    reinterpret_cast<char*>(&_impl_.lat_)) + sizeof(_impl_.lon_));
  // @@protoc_insertion_point(copy_constructor:TCsP.LatLonPair)
}

inline void TCsP_LatLonPair::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.lat_){0}
    , decltype(_impl_.lon_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TCsP_LatLonPair::~TCsP_LatLonPair() {
  // @@protoc_insertion_point(destructor:TCsP.LatLonPair)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TCsP_LatLonPair::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TCsP_LatLonPair::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TCsP_LatLonPair::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP.LatLonPair)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.lat_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.lon_) -
      reinterpret_cast<char*>(&_impl_.lat_)) + sizeof(_impl_.lon_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TCsP_LatLonPair::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float lat = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.lat_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float lon = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.lon_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TCsP_LatLonPair::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TCsP.LatLonPair)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float lat = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = this->_internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_lat(), target);
  }

  // float lon = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lon = this->_internal_lon();
  uint32_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_lon(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP.LatLonPair)
  return target;
}

size_t TCsP_LatLonPair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TCsP.LatLonPair)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float lat = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = this->_internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    total_size += 1 + 4;
  }

  // float lon = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lon = this->_internal_lon();
  uint32_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TCsP_LatLonPair::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TCsP_LatLonPair::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TCsP_LatLonPair::GetClassData() const { return &_class_data_; }


void TCsP_LatLonPair::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TCsP_LatLonPair*>(&to_msg);
  auto& from = static_cast<const TCsP_LatLonPair&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP.LatLonPair)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = from._internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    _this->_internal_set_lat(from._internal_lat());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lon = from._internal_lon();
  uint32_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    _this->_internal_set_lon(from._internal_lon());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TCsP_LatLonPair::CopyFrom(const TCsP_LatLonPair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TCsP.LatLonPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TCsP_LatLonPair::IsInitialized() const {
  return true;
}

void TCsP_LatLonPair::InternalSwap(TCsP_LatLonPair* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_.lon_)
      + sizeof(TCsP_LatLonPair::_impl_.lon_)
      - PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_.lat_)>(
          reinterpret_cast<char*>(&_impl_.lat_),
          reinterpret_cast<char*>(&other->_impl_.lat_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TCsP_LatLonPair::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TCsP_2eproto_getter, &descriptor_table_TCsP_2eproto_once,
      file_level_metadata_TCsP_2eproto[1]);
}

// ===================================================================

class TCsP_VorCellsIndex::_Internal {
 public:
};

TCsP_VorCellsIndex::TCsP_VorCellsIndex(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TCsP.VorCellsIndex)
}
TCsP_VorCellsIndex::TCsP_VorCellsIndex(const TCsP_VorCellsIndex& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TCsP_VorCellsIndex* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.vorcellsindex_){from._impl_.vorcellsindex_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:TCsP.VorCellsIndex)
}

inline void TCsP_VorCellsIndex::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.vorcellsindex_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TCsP_VorCellsIndex::~TCsP_VorCellsIndex() {
  // @@protoc_insertion_point(destructor:TCsP.VorCellsIndex)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TCsP_VorCellsIndex::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.vorcellsindex_.~RepeatedPtrField();
}

void TCsP_VorCellsIndex::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TCsP_VorCellsIndex::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP.VorCellsIndex)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.vorcellsindex_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TCsP_VorCellsIndex::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .TCsP.IndexPair vorCellsIndex = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_vorcellsindex(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TCsP_VorCellsIndex::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TCsP.VorCellsIndex)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .TCsP.IndexPair vorCellsIndex = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_vorcellsindex_size()); i < n; i++) {
    const auto& repfield = this->_internal_vorcellsindex(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP.VorCellsIndex)
  return target;
}

size_t TCsP_VorCellsIndex::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TCsP.VorCellsIndex)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .TCsP.IndexPair vorCellsIndex = 1;
  total_size += 1UL * this->_internal_vorcellsindex_size();
  for (const auto& msg : this->_impl_.vorcellsindex_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TCsP_VorCellsIndex::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TCsP_VorCellsIndex::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TCsP_VorCellsIndex::GetClassData() const { return &_class_data_; }


void TCsP_VorCellsIndex::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TCsP_VorCellsIndex*>(&to_msg);
  auto& from = static_cast<const TCsP_VorCellsIndex&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP.VorCellsIndex)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.vorcellsindex_.MergeFrom(from._impl_.vorcellsindex_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TCsP_VorCellsIndex::CopyFrom(const TCsP_VorCellsIndex& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TCsP.VorCellsIndex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TCsP_VorCellsIndex::IsInitialized() const {
  return true;
}

void TCsP_VorCellsIndex::InternalSwap(TCsP_VorCellsIndex* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.vorcellsindex_.InternalSwap(&other->_impl_.vorcellsindex_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TCsP_VorCellsIndex::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TCsP_2eproto_getter, &descriptor_table_TCsP_2eproto_once,
      file_level_metadata_TCsP_2eproto[2]);
}

// ===================================================================

class TCsP_Typhoon::_Internal {
 public:
};

TCsP_Typhoon::TCsP_Typhoon(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TCsP.Typhoon)
}
TCsP_Typhoon::TCsP_Typhoon(const TCsP_Typhoon& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TCsP_Typhoon* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.maxvorcells_){from._impl_.maxvorcells_}
    , decltype(_impl_.geocenters_){from._impl_.geocenters_}
    , decltype(_impl_.vorscellsindex_){from._impl_.vorscellsindex_}
    , decltype(_impl_.starttimeindex_){}
    , decltype(_impl_.endtimeindex_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.starttimeindex_, &from._impl_.starttimeindex_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.endtimeindex_) -
    reinterpret_cast<char*>(&_impl_.starttimeindex_)) + sizeof(_impl_.endtimeindex_));
  // @@protoc_insertion_point(copy_constructor:TCsP.Typhoon)
}

inline void TCsP_Typhoon::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.maxvorcells_){arena}
    , decltype(_impl_.geocenters_){arena}
    , decltype(_impl_.vorscellsindex_){arena}
    , decltype(_impl_.starttimeindex_){0}
    , decltype(_impl_.endtimeindex_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TCsP_Typhoon::~TCsP_Typhoon() {
  // @@protoc_insertion_point(destructor:TCsP.Typhoon)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TCsP_Typhoon::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.maxvorcells_.~RepeatedPtrField();
  _impl_.geocenters_.~RepeatedPtrField();
  _impl_.vorscellsindex_.~RepeatedPtrField();
}

void TCsP_Typhoon::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TCsP_Typhoon::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP.Typhoon)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.maxvorcells_.Clear();
  _impl_.geocenters_.Clear();
  _impl_.vorscellsindex_.Clear();
  ::memset(&_impl_.starttimeindex_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.endtimeindex_) -
      reinterpret_cast<char*>(&_impl_.starttimeindex_)) + sizeof(_impl_.endtimeindex_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TCsP_Typhoon::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .TCsP.IndexPair maxVorCells = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_maxvorcells(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .TCsP.LatLonPair geoCenters = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_geocenters(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 startTimeIndex = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.starttimeindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 endTimeIndex = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.endtimeindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_vorscellsindex(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TCsP_Typhoon::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TCsP.Typhoon)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .TCsP.IndexPair maxVorCells = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_maxvorcells_size()); i < n; i++) {
    const auto& repfield = this->_internal_maxvorcells(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .TCsP.LatLonPair geoCenters = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_geocenters_size()); i < n; i++) {
    const auto& repfield = this->_internal_geocenters(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int32 startTimeIndex = 3;
  if (this->_internal_starttimeindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_starttimeindex(), target);
  }

  // int32 endTimeIndex = 4;
  if (this->_internal_endtimeindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_endtimeindex(), target);
  }

  // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_vorscellsindex_size()); i < n; i++) {
    const auto& repfield = this->_internal_vorscellsindex(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP.Typhoon)
  return target;
}

size_t TCsP_Typhoon::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TCsP.Typhoon)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .TCsP.IndexPair maxVorCells = 1;
  total_size += 1UL * this->_internal_maxvorcells_size();
  for (const auto& msg : this->_impl_.maxvorcells_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .TCsP.LatLonPair geoCenters = 2;
  total_size += 1UL * this->_internal_geocenters_size();
  for (const auto& msg : this->_impl_.geocenters_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
  total_size += 1UL * this->_internal_vorscellsindex_size();
  for (const auto& msg : this->_impl_.vorscellsindex_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 startTimeIndex = 3;
  if (this->_internal_starttimeindex() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_starttimeindex());
  }

  // int32 endTimeIndex = 4;
  if (this->_internal_endtimeindex() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_endtimeindex());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TCsP_Typhoon::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TCsP_Typhoon::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TCsP_Typhoon::GetClassData() const { return &_class_data_; }


void TCsP_Typhoon::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TCsP_Typhoon*>(&to_msg);
  auto& from = static_cast<const TCsP_Typhoon&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP.Typhoon)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.maxvorcells_.MergeFrom(from._impl_.maxvorcells_);
  _this->_impl_.geocenters_.MergeFrom(from._impl_.geocenters_);
  _this->_impl_.vorscellsindex_.MergeFrom(from._impl_.vorscellsindex_);
  if (from._internal_starttimeindex() != 0) {
    _this->_internal_set_starttimeindex(from._internal_starttimeindex());
  }
  if (from._internal_endtimeindex() != 0) {
    _this->_internal_set_endtimeindex(from._internal_endtimeindex());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TCsP_Typhoon::CopyFrom(const TCsP_Typhoon& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TCsP.Typhoon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TCsP_Typhoon::IsInitialized() const {
  return true;
}

void TCsP_Typhoon::InternalSwap(TCsP_Typhoon* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.maxvorcells_.InternalSwap(&other->_impl_.maxvorcells_);
  _impl_.geocenters_.InternalSwap(&other->_impl_.geocenters_);
  _impl_.vorscellsindex_.InternalSwap(&other->_impl_.vorscellsindex_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.endtimeindex_)
      + sizeof(TCsP_Typhoon::_impl_.endtimeindex_)
      - PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.starttimeindex_)>(
          reinterpret_cast<char*>(&_impl_.starttimeindex_),
          reinterpret_cast<char*>(&other->_impl_.starttimeindex_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TCsP_Typhoon::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TCsP_2eproto_getter, &descriptor_table_TCsP_2eproto_once,
      file_level_metadata_TCsP_2eproto[3]);
}

// ===================================================================

class TCsP::_Internal {
 public:
};

TCsP::TCsP(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TCsP)
}
TCsP::TCsP(const TCsP& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TCsP* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.typhoons_){from._impl_.typhoons_}
    , decltype(_impl_.lats_){from._impl_.lats_}
    , decltype(_impl_.lons_){from._impl_.lons_}
    , decltype(_impl_.timeunits_){}
    , decltype(_impl_.time_noleap_){}
    , decltype(_impl_.firsttimevalue_){}
    , decltype(_impl_.timehourinterval_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.timeunits_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timeunits_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timeunits().empty()) {
    _this->_impl_.timeunits_.Set(from._internal_timeunits(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.time_noleap_, &from._impl_.time_noleap_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timehourinterval_) -
    reinterpret_cast<char*>(&_impl_.time_noleap_)) + sizeof(_impl_.timehourinterval_));
  // @@protoc_insertion_point(copy_constructor:TCsP)
}

inline void TCsP::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.typhoons_){arena}
    , decltype(_impl_.lats_){arena}
    , decltype(_impl_.lons_){arena}
    , decltype(_impl_.timeunits_){}
    , decltype(_impl_.time_noleap_){false}
    , decltype(_impl_.firsttimevalue_){0}
    , decltype(_impl_.timehourinterval_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.timeunits_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timeunits_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TCsP::~TCsP() {
  // @@protoc_insertion_point(destructor:TCsP)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TCsP::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.typhoons_.~RepeatedPtrField();
  _impl_.lats_.~RepeatedField();
  _impl_.lons_.~RepeatedField();
  _impl_.timeunits_.Destroy();
}

void TCsP::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TCsP::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.typhoons_.Clear();
  _impl_.lats_.Clear();
  _impl_.lons_.Clear();
  _impl_.timeunits_.ClearToEmpty();
  ::memset(&_impl_.time_noleap_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timehourinterval_) -
      reinterpret_cast<char*>(&_impl_.time_noleap_)) + sizeof(_impl_.timehourinterval_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TCsP::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .TCsP.Typhoon typhoons = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_typhoons(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string timeUnits = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_timeunits();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TCsP.timeUnits"));
        } else
          goto handle_unusual;
        continue;
      // bool time_noleap = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.time_noleap_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 firstTimeValue = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.firsttimevalue_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 timeHourInterval = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.timehourinterval_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated float lats = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_lats(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 53) {
          _internal_add_lats(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated float lons = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_lons(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 61) {
          _internal_add_lons(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TCsP::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TCsP)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .TCsP.Typhoon typhoons = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_typhoons_size()); i < n; i++) {
    const auto& repfield = this->_internal_typhoons(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // string timeUnits = 2;
  if (!this->_internal_timeunits().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timeunits().data(), static_cast<int>(this->_internal_timeunits().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TCsP.timeUnits");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_timeunits(), target);
  }

  // bool time_noleap = 3;
  if (this->_internal_time_noleap() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_time_noleap(), target);
  }

  // int32 firstTimeValue = 4;
  if (this->_internal_firsttimevalue() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_firsttimevalue(), target);
  }

  // int32 timeHourInterval = 5;
  if (this->_internal_timehourinterval() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_timehourinterval(), target);
  }

  // repeated float lats = 6;
  if (this->_internal_lats_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_lats(), target);
  }

  // repeated float lons = 7;
  if (this->_internal_lons_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_lons(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP)
  return target;
}

size_t TCsP::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TCsP)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .TCsP.Typhoon typhoons = 1;
  total_size += 1UL * this->_internal_typhoons_size();
  for (const auto& msg : this->_impl_.typhoons_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated float lats = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_lats_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated float lons = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_lons_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string timeUnits = 2;
  if (!this->_internal_timeunits().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timeunits());
  }

  // bool time_noleap = 3;
  if (this->_internal_time_noleap() != 0) {
    total_size += 1 + 1;
  }

  // int32 firstTimeValue = 4;
  if (this->_internal_firsttimevalue() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_firsttimevalue());
  }

  // int32 timeHourInterval = 5;
  if (this->_internal_timehourinterval() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_timehourinterval());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TCsP::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TCsP::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TCsP::GetClassData() const { return &_class_data_; }


void TCsP::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TCsP*>(&to_msg);
  auto& from = static_cast<const TCsP&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.typhoons_.MergeFrom(from._impl_.typhoons_);
  _this->_impl_.lats_.MergeFrom(from._impl_.lats_);
  _this->_impl_.lons_.MergeFrom(from._impl_.lons_);
  if (!from._internal_timeunits().empty()) {
    _this->_internal_set_timeunits(from._internal_timeunits());
  }
  if (from._internal_time_noleap() != 0) {
    _this->_internal_set_time_noleap(from._internal_time_noleap());
  }
  if (from._internal_firsttimevalue() != 0) {
    _this->_internal_set_firsttimevalue(from._internal_firsttimevalue());
  }
  if (from._internal_timehourinterval() != 0) {
    _this->_internal_set_timehourinterval(from._internal_timehourinterval());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TCsP::CopyFrom(const TCsP& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TCsP)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TCsP::IsInitialized() const {
  return true;
}

void TCsP::InternalSwap(TCsP* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.typhoons_.InternalSwap(&other->_impl_.typhoons_);
  _impl_.lats_.InternalSwap(&other->_impl_.lats_);
  _impl_.lons_.InternalSwap(&other->_impl_.lons_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timeunits_, lhs_arena,
      &other->_impl_.timeunits_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.timehourinterval_)
      + sizeof(TCsP::_impl_.timehourinterval_)
      - PROTOBUF_FIELD_OFFSET(TCsP, _impl_.time_noleap_)>(
          reinterpret_cast<char*>(&_impl_.time_noleap_),
          reinterpret_cast<char*>(&other->_impl_.time_noleap_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TCsP::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TCsP_2eproto_getter, &descriptor_table_TCsP_2eproto_once,
      file_level_metadata_TCsP_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TCsP_IndexPair*
Arena::CreateMaybeMessage< ::TCsP_IndexPair >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TCsP_IndexPair >(arena);
}
template<> PROTOBUF_NOINLINE ::TCsP_LatLonPair*
Arena::CreateMaybeMessage< ::TCsP_LatLonPair >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TCsP_LatLonPair >(arena);
}
template<> PROTOBUF_NOINLINE ::TCsP_VorCellsIndex*
Arena::CreateMaybeMessage< ::TCsP_VorCellsIndex >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TCsP_VorCellsIndex >(arena);
}
template<> PROTOBUF_NOINLINE ::TCsP_Typhoon*
Arena::CreateMaybeMessage< ::TCsP_Typhoon >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TCsP_Typhoon >(arena);
}
template<> PROTOBUF_NOINLINE ::TCsP*
Arena::CreateMaybeMessage< ::TCsP >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TCsP >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
