// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TCsP.proto
// Protobuf C++ Version: 6.33.4

#ifndef TCsP_2eproto_2epb_2eh
#define TCsP_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_TCsP_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_TCsP_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_TCsP_2eproto;
}  // extern "C"
class TCsP;
struct TCsPDefaultTypeInternal;
extern TCsPDefaultTypeInternal _TCsP_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TCsP_class_data_;
class TCsP_IndexPair;
struct TCsP_IndexPairDefaultTypeInternal;
extern TCsP_IndexPairDefaultTypeInternal _TCsP_IndexPair_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TCsP_IndexPair_class_data_;
class TCsP_LatLonPair;
struct TCsP_LatLonPairDefaultTypeInternal;
extern TCsP_LatLonPairDefaultTypeInternal _TCsP_LatLonPair_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TCsP_LatLonPair_class_data_;
class TCsP_Typhoon;
struct TCsP_TyphoonDefaultTypeInternal;
extern TCsP_TyphoonDefaultTypeInternal _TCsP_Typhoon_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TCsP_Typhoon_class_data_;
class TCsP_VorCellsIndex;
struct TCsP_VorCellsIndexDefaultTypeInternal;
extern TCsP_VorCellsIndexDefaultTypeInternal _TCsP_VorCellsIndex_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TCsP_VorCellsIndex_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class TCsP_LatLonPair final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TCsP.LatLonPair) */ {
 public:
  inline TCsP_LatLonPair() : TCsP_LatLonPair(nullptr) {}
  ~TCsP_LatLonPair() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TCsP_LatLonPair* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TCsP_LatLonPair));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TCsP_LatLonPair(::google::protobuf::internal::ConstantInitialized);

  inline TCsP_LatLonPair(const TCsP_LatLonPair& from) : TCsP_LatLonPair(nullptr, from) {}
  inline TCsP_LatLonPair(TCsP_LatLonPair&& from) noexcept
      : TCsP_LatLonPair(nullptr, ::std::move(from)) {}
  inline TCsP_LatLonPair& operator=(const TCsP_LatLonPair& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP_LatLonPair& operator=(TCsP_LatLonPair&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP_LatLonPair& default_instance() {
    return *reinterpret_cast<const TCsP_LatLonPair*>(
        &_TCsP_LatLonPair_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TCsP_LatLonPair& a, TCsP_LatLonPair& b) { a.Swap(&b); }
  inline void Swap(TCsP_LatLonPair* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP_LatLonPair* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP_LatLonPair* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TCsP_LatLonPair>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TCsP_LatLonPair& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TCsP_LatLonPair& from) { TCsP_LatLonPair::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TCsP_LatLonPair* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TCsP.LatLonPair"; }

  explicit TCsP_LatLonPair(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TCsP_LatLonPair(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TCsP_LatLonPair& from);
  TCsP_LatLonPair(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TCsP_LatLonPair&& from) noexcept
      : TCsP_LatLonPair(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLatFieldNumber = 1,
    kLonFieldNumber = 2,
  };
  // float lat = 1;
  void clear_lat() ;
  float lat() const;
  void set_lat(float value);

  private:
  float _internal_lat() const;
  void _internal_set_lat(float value);

  public:
  // float lon = 2;
  void clear_lon() ;
  float lon() const;
  void set_lon(float value);

  private:
  float _internal_lon() const;
  void _internal_set_lon(float value);

  public:
  // @@protoc_insertion_point(class_scope:TCsP.LatLonPair)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TCsP_LatLonPair& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float lat_;
    float lon_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TCsP_LatLonPair_class_data_;
// -------------------------------------------------------------------

class TCsP_IndexPair final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TCsP.IndexPair) */ {
 public:
  inline TCsP_IndexPair() : TCsP_IndexPair(nullptr) {}
  ~TCsP_IndexPair() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TCsP_IndexPair* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TCsP_IndexPair));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TCsP_IndexPair(::google::protobuf::internal::ConstantInitialized);

  inline TCsP_IndexPair(const TCsP_IndexPair& from) : TCsP_IndexPair(nullptr, from) {}
  inline TCsP_IndexPair(TCsP_IndexPair&& from) noexcept
      : TCsP_IndexPair(nullptr, ::std::move(from)) {}
  inline TCsP_IndexPair& operator=(const TCsP_IndexPair& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP_IndexPair& operator=(TCsP_IndexPair&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP_IndexPair& default_instance() {
    return *reinterpret_cast<const TCsP_IndexPair*>(
        &_TCsP_IndexPair_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TCsP_IndexPair& a, TCsP_IndexPair& b) { a.Swap(&b); }
  inline void Swap(TCsP_IndexPair* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP_IndexPair* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP_IndexPair* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TCsP_IndexPair>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TCsP_IndexPair& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TCsP_IndexPair& from) { TCsP_IndexPair::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TCsP_IndexPair* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TCsP.IndexPair"; }

  explicit TCsP_IndexPair(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TCsP_IndexPair(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TCsP_IndexPair& from);
  TCsP_IndexPair(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TCsP_IndexPair&& from) noexcept
      : TCsP_IndexPair(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLatIndexFieldNumber = 1,
    kLonIndexFieldNumber = 2,
  };
  // int32 latIndex = 1;
  void clear_latindex() ;
  ::int32_t latindex() const;
  void set_latindex(::int32_t value);

  private:
  ::int32_t _internal_latindex() const;
  void _internal_set_latindex(::int32_t value);

  public:
  // int32 lonIndex = 2;
  void clear_lonindex() ;
  ::int32_t lonindex() const;
  void set_lonindex(::int32_t value);

  private:
  ::int32_t _internal_lonindex() const;
  void _internal_set_lonindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:TCsP.IndexPair)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TCsP_IndexPair& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t latindex_;
    ::int32_t lonindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TCsP_IndexPair_class_data_;
// -------------------------------------------------------------------

class TCsP_VorCellsIndex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TCsP.VorCellsIndex) */ {
 public:
  inline TCsP_VorCellsIndex() : TCsP_VorCellsIndex(nullptr) {}
  ~TCsP_VorCellsIndex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TCsP_VorCellsIndex* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TCsP_VorCellsIndex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TCsP_VorCellsIndex(::google::protobuf::internal::ConstantInitialized);

  inline TCsP_VorCellsIndex(const TCsP_VorCellsIndex& from) : TCsP_VorCellsIndex(nullptr, from) {}
  inline TCsP_VorCellsIndex(TCsP_VorCellsIndex&& from) noexcept
      : TCsP_VorCellsIndex(nullptr, ::std::move(from)) {}
  inline TCsP_VorCellsIndex& operator=(const TCsP_VorCellsIndex& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP_VorCellsIndex& operator=(TCsP_VorCellsIndex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP_VorCellsIndex& default_instance() {
    return *reinterpret_cast<const TCsP_VorCellsIndex*>(
        &_TCsP_VorCellsIndex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(TCsP_VorCellsIndex& a, TCsP_VorCellsIndex& b) { a.Swap(&b); }
  inline void Swap(TCsP_VorCellsIndex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP_VorCellsIndex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP_VorCellsIndex* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TCsP_VorCellsIndex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TCsP_VorCellsIndex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TCsP_VorCellsIndex& from) { TCsP_VorCellsIndex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TCsP_VorCellsIndex* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TCsP.VorCellsIndex"; }

  explicit TCsP_VorCellsIndex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TCsP_VorCellsIndex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TCsP_VorCellsIndex& from);
  TCsP_VorCellsIndex(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TCsP_VorCellsIndex&& from) noexcept
      : TCsP_VorCellsIndex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVorCellsIndexFieldNumber = 1,
  };
  // repeated .TCsP.IndexPair vorCellsIndex = 1;
  int vorcellsindex_size() const;
  private:
  int _internal_vorcellsindex_size() const;

  public:
  void clear_vorcellsindex() ;
  ::TCsP_IndexPair* PROTOBUF_NONNULL mutable_vorcellsindex(int index);
  ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>* PROTOBUF_NONNULL mutable_vorcellsindex();

  private:
  const ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>& _internal_vorcellsindex() const;
  ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>* PROTOBUF_NONNULL _internal_mutable_vorcellsindex();
  public:
  const ::TCsP_IndexPair& vorcellsindex(int index) const;
  ::TCsP_IndexPair* PROTOBUF_NONNULL add_vorcellsindex();
  const ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>& vorcellsindex() const;
  // @@protoc_insertion_point(class_scope:TCsP.VorCellsIndex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TCsP_VorCellsIndex& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::TCsP_IndexPair > vorcellsindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TCsP_VorCellsIndex_class_data_;
// -------------------------------------------------------------------

class TCsP_Typhoon final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TCsP.Typhoon) */ {
 public:
  inline TCsP_Typhoon() : TCsP_Typhoon(nullptr) {}
  ~TCsP_Typhoon() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TCsP_Typhoon* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TCsP_Typhoon));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TCsP_Typhoon(::google::protobuf::internal::ConstantInitialized);

  inline TCsP_Typhoon(const TCsP_Typhoon& from) : TCsP_Typhoon(nullptr, from) {}
  inline TCsP_Typhoon(TCsP_Typhoon&& from) noexcept
      : TCsP_Typhoon(nullptr, ::std::move(from)) {}
  inline TCsP_Typhoon& operator=(const TCsP_Typhoon& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP_Typhoon& operator=(TCsP_Typhoon&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP_Typhoon& default_instance() {
    return *reinterpret_cast<const TCsP_Typhoon*>(
        &_TCsP_Typhoon_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(TCsP_Typhoon& a, TCsP_Typhoon& b) { a.Swap(&b); }
  inline void Swap(TCsP_Typhoon* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP_Typhoon* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP_Typhoon* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TCsP_Typhoon>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TCsP_Typhoon& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TCsP_Typhoon& from) { TCsP_Typhoon::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TCsP_Typhoon* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TCsP.Typhoon"; }

  explicit TCsP_Typhoon(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TCsP_Typhoon(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TCsP_Typhoon& from);
  TCsP_Typhoon(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TCsP_Typhoon&& from) noexcept
      : TCsP_Typhoon(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMaxVorCellsFieldNumber = 1,
    kGeoCentersFieldNumber = 2,
    kVorsCellsIndexFieldNumber = 5,
    kStartTimeIndexFieldNumber = 3,
    kEndTimeIndexFieldNumber = 4,
  };
  // repeated .TCsP.IndexPair maxVorCells = 1;
  int maxvorcells_size() const;
  private:
  int _internal_maxvorcells_size() const;

  public:
  void clear_maxvorcells() ;
  ::TCsP_IndexPair* PROTOBUF_NONNULL mutable_maxvorcells(int index);
  ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>* PROTOBUF_NONNULL mutable_maxvorcells();

  private:
  const ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>& _internal_maxvorcells() const;
  ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>* PROTOBUF_NONNULL _internal_mutable_maxvorcells();
  public:
  const ::TCsP_IndexPair& maxvorcells(int index) const;
  ::TCsP_IndexPair* PROTOBUF_NONNULL add_maxvorcells();
  const ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>& maxvorcells() const;
  // repeated .TCsP.LatLonPair geoCenters = 2;
  int geocenters_size() const;
  private:
  int _internal_geocenters_size() const;

  public:
  void clear_geocenters() ;
  ::TCsP_LatLonPair* PROTOBUF_NONNULL mutable_geocenters(int index);
  ::google::protobuf::RepeatedPtrField<::TCsP_LatLonPair>* PROTOBUF_NONNULL mutable_geocenters();

  private:
  const ::google::protobuf::RepeatedPtrField<::TCsP_LatLonPair>& _internal_geocenters() const;
  ::google::protobuf::RepeatedPtrField<::TCsP_LatLonPair>* PROTOBUF_NONNULL _internal_mutable_geocenters();
  public:
  const ::TCsP_LatLonPair& geocenters(int index) const;
  ::TCsP_LatLonPair* PROTOBUF_NONNULL add_geocenters();
  const ::google::protobuf::RepeatedPtrField<::TCsP_LatLonPair>& geocenters() const;
  // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
  int vorscellsindex_size() const;
  private:
  int _internal_vorscellsindex_size() const;

  public:
  void clear_vorscellsindex() ;
  ::TCsP_VorCellsIndex* PROTOBUF_NONNULL mutable_vorscellsindex(int index);
  ::google::protobuf::RepeatedPtrField<::TCsP_VorCellsIndex>* PROTOBUF_NONNULL mutable_vorscellsindex();

  private:
  const ::google::protobuf::RepeatedPtrField<::TCsP_VorCellsIndex>& _internal_vorscellsindex() const;
  ::google::protobuf::RepeatedPtrField<::TCsP_VorCellsIndex>* PROTOBUF_NONNULL _internal_mutable_vorscellsindex();
  public:
  const ::TCsP_VorCellsIndex& vorscellsindex(int index) const;
  ::TCsP_VorCellsIndex* PROTOBUF_NONNULL add_vorscellsindex();
  const ::google::protobuf::RepeatedPtrField<::TCsP_VorCellsIndex>& vorscellsindex() const;
  // int32 startTimeIndex = 3;
  void clear_starttimeindex() ;
  ::int32_t starttimeindex() const;
  void set_starttimeindex(::int32_t value);

  private:
  ::int32_t _internal_starttimeindex() const;
  void _internal_set_starttimeindex(::int32_t value);

  public:
  // int32 endTimeIndex = 4;
  void clear_endtimeindex() ;
  ::int32_t endtimeindex() const;
  void set_endtimeindex(::int32_t value);

  private:
  ::int32_t _internal_endtimeindex() const;
  void _internal_set_endtimeindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:TCsP.Typhoon)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TCsP_Typhoon& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::TCsP_IndexPair > maxvorcells_;
    ::google::protobuf::RepeatedPtrField< ::TCsP_LatLonPair > geocenters_;
    ::google::protobuf::RepeatedPtrField< ::TCsP_VorCellsIndex > vorscellsindex_;
    ::int32_t starttimeindex_;
    ::int32_t endtimeindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TCsP_Typhoon_class_data_;
// -------------------------------------------------------------------

class TCsP final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TCsP) */ {
 public:
  inline TCsP() : TCsP(nullptr) {}
  ~TCsP() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TCsP* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TCsP));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TCsP(::google::protobuf::internal::ConstantInitialized);

  inline TCsP(const TCsP& from) : TCsP(nullptr, from) {}
  inline TCsP(TCsP&& from) noexcept
      : TCsP(nullptr, ::std::move(from)) {}
  inline TCsP& operator=(const TCsP& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP& operator=(TCsP&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP& default_instance() {
    return *reinterpret_cast<const TCsP*>(
        &_TCsP_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(TCsP& a, TCsP& b) { a.Swap(&b); }
  inline void Swap(TCsP* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TCsP>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TCsP& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TCsP& from) { TCsP::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TCsP* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TCsP"; }

  explicit TCsP(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TCsP(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TCsP& from);
  TCsP(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TCsP&& from) noexcept
      : TCsP(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using IndexPair = TCsP_IndexPair;
  using LatLonPair = TCsP_LatLonPair;
  using VorCellsIndex = TCsP_VorCellsIndex;
  using Typhoon = TCsP_Typhoon;

  // accessors -------------------------------------------------------
  enum : int {
    kTyphoonsFieldNumber = 1,
    kLatsFieldNumber = 6,
    kLonsFieldNumber = 7,
    kTimeUnitsFieldNumber = 2,
    kTimeNoleapFieldNumber = 3,
    kFirstTimeValueFieldNumber = 4,
    kTimeHourIntervalFieldNumber = 5,
  };
  // repeated .TCsP.Typhoon typhoons = 1;
  int typhoons_size() const;
  private:
  int _internal_typhoons_size() const;

  public:
  void clear_typhoons() ;
  ::TCsP_Typhoon* PROTOBUF_NONNULL mutable_typhoons(int index);
  ::google::protobuf::RepeatedPtrField<::TCsP_Typhoon>* PROTOBUF_NONNULL mutable_typhoons();

  private:
  const ::google::protobuf::RepeatedPtrField<::TCsP_Typhoon>& _internal_typhoons() const;
  ::google::protobuf::RepeatedPtrField<::TCsP_Typhoon>* PROTOBUF_NONNULL _internal_mutable_typhoons();
  public:
  const ::TCsP_Typhoon& typhoons(int index) const;
  ::TCsP_Typhoon* PROTOBUF_NONNULL add_typhoons();
  const ::google::protobuf::RepeatedPtrField<::TCsP_Typhoon>& typhoons() const;
  // repeated float lats = 6;
  int lats_size() const;
  private:
  int _internal_lats_size() const;

  public:
  void clear_lats() ;
  float lats(int index) const;
  void set_lats(int index, float value);
  void add_lats(float value);
  const ::google::protobuf::RepeatedField<float>& lats() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_lats();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_lats() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_lats();

  public:
  // repeated float lons = 7;
  int lons_size() const;
  private:
  int _internal_lons_size() const;

  public:
  void clear_lons() ;
  float lons(int index) const;
  void set_lons(int index, float value);
  void add_lons(float value);
  const ::google::protobuf::RepeatedField<float>& lons() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_lons();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_lons() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_lons();

  public:
  // string timeUnits = 2;
  void clear_timeunits() ;
  const ::std::string& timeunits() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_timeunits(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_timeunits();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_timeunits();
  void set_allocated_timeunits(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_timeunits() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_timeunits(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_timeunits();

  public:
  // bool time_noleap = 3;
  void clear_time_noleap() ;
  bool time_noleap() const;
  void set_time_noleap(bool value);

  private:
  bool _internal_time_noleap() const;
  void _internal_set_time_noleap(bool value);

  public:
  // int32 firstTimeValue = 4;
  void clear_firsttimevalue() ;
  ::int32_t firsttimevalue() const;
  void set_firsttimevalue(::int32_t value);

  private:
  ::int32_t _internal_firsttimevalue() const;
  void _internal_set_firsttimevalue(::int32_t value);

  public:
  // int32 timeHourInterval = 5;
  void clear_timehourinterval() ;
  ::int32_t timehourinterval() const;
  void set_timehourinterval(::int32_t value);

  private:
  ::int32_t _internal_timehourinterval() const;
  void _internal_set_timehourinterval(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:TCsP)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   1, 22,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TCsP& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::TCsP_Typhoon > typhoons_;
    ::google::protobuf::RepeatedField<float> lats_;
    ::google::protobuf::RepeatedField<float> lons_;
    ::google::protobuf::internal::ArenaStringPtr timeunits_;
    bool time_noleap_;
    ::int32_t firsttimevalue_;
    ::int32_t timehourinterval_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TCsP_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TCsP_IndexPair

// int32 latIndex = 1;
inline void TCsP_IndexPair::clear_latindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latindex_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t TCsP_IndexPair::latindex() const {
  // @@protoc_insertion_point(field_get:TCsP.IndexPair.latIndex)
  return _internal_latindex();
}
inline void TCsP_IndexPair::set_latindex(::int32_t value) {
  _internal_set_latindex(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:TCsP.IndexPair.latIndex)
}
inline ::int32_t TCsP_IndexPair::_internal_latindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.latindex_;
}
inline void TCsP_IndexPair::_internal_set_latindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latindex_ = value;
}

// int32 lonIndex = 2;
inline void TCsP_IndexPair::clear_lonindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lonindex_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t TCsP_IndexPair::lonindex() const {
  // @@protoc_insertion_point(field_get:TCsP.IndexPair.lonIndex)
  return _internal_lonindex();
}
inline void TCsP_IndexPair::set_lonindex(::int32_t value) {
  _internal_set_lonindex(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:TCsP.IndexPair.lonIndex)
}
inline ::int32_t TCsP_IndexPair::_internal_lonindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lonindex_;
}
inline void TCsP_IndexPair::_internal_set_lonindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lonindex_ = value;
}

// -------------------------------------------------------------------

// TCsP_LatLonPair

// float lat = 1;
inline void TCsP_LatLonPair::clear_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline float TCsP_LatLonPair::lat() const {
  // @@protoc_insertion_point(field_get:TCsP.LatLonPair.lat)
  return _internal_lat();
}
inline void TCsP_LatLonPair::set_lat(float value) {
  _internal_set_lat(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:TCsP.LatLonPair.lat)
}
inline float TCsP_LatLonPair::_internal_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lat_;
}
inline void TCsP_LatLonPair::_internal_set_lat(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_ = value;
}

// float lon = 2;
inline void TCsP_LatLonPair::clear_lon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline float TCsP_LatLonPair::lon() const {
  // @@protoc_insertion_point(field_get:TCsP.LatLonPair.lon)
  return _internal_lon();
}
inline void TCsP_LatLonPair::set_lon(float value) {
  _internal_set_lon(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:TCsP.LatLonPair.lon)
}
inline float TCsP_LatLonPair::_internal_lon() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lon_;
}
inline void TCsP_LatLonPair::_internal_set_lon(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_ = value;
}

// -------------------------------------------------------------------

// TCsP_VorCellsIndex

// repeated .TCsP.IndexPair vorCellsIndex = 1;
inline int TCsP_VorCellsIndex::_internal_vorcellsindex_size() const {
  return _internal_vorcellsindex().size();
}
inline int TCsP_VorCellsIndex::vorcellsindex_size() const {
  return _internal_vorcellsindex_size();
}
inline void TCsP_VorCellsIndex::clear_vorcellsindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vorcellsindex_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::TCsP_IndexPair* PROTOBUF_NONNULL TCsP_VorCellsIndex::mutable_vorcellsindex(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:TCsP.VorCellsIndex.vorCellsIndex)
  return _internal_mutable_vorcellsindex()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>* PROTOBUF_NONNULL TCsP_VorCellsIndex::mutable_vorcellsindex()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:TCsP.VorCellsIndex.vorCellsIndex)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vorcellsindex();
}
inline const ::TCsP_IndexPair& TCsP_VorCellsIndex::vorcellsindex(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TCsP.VorCellsIndex.vorCellsIndex)
  return _internal_vorcellsindex().Get(index);
}
inline ::TCsP_IndexPair* PROTOBUF_NONNULL TCsP_VorCellsIndex::add_vorcellsindex()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::TCsP_IndexPair* _add =
      _internal_mutable_vorcellsindex()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:TCsP.VorCellsIndex.vorCellsIndex)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>& TCsP_VorCellsIndex::vorcellsindex() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TCsP.VorCellsIndex.vorCellsIndex)
  return _internal_vorcellsindex();
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>&
TCsP_VorCellsIndex::_internal_vorcellsindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vorcellsindex_;
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>* PROTOBUF_NONNULL
TCsP_VorCellsIndex::_internal_mutable_vorcellsindex() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vorcellsindex_;
}

// -------------------------------------------------------------------

// TCsP_Typhoon

// repeated .TCsP.IndexPair maxVorCells = 1;
inline int TCsP_Typhoon::_internal_maxvorcells_size() const {
  return _internal_maxvorcells().size();
}
inline int TCsP_Typhoon::maxvorcells_size() const {
  return _internal_maxvorcells_size();
}
inline void TCsP_Typhoon::clear_maxvorcells() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maxvorcells_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::TCsP_IndexPair* PROTOBUF_NONNULL TCsP_Typhoon::mutable_maxvorcells(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:TCsP.Typhoon.maxVorCells)
  return _internal_mutable_maxvorcells()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>* PROTOBUF_NONNULL TCsP_Typhoon::mutable_maxvorcells()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:TCsP.Typhoon.maxVorCells)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_maxvorcells();
}
inline const ::TCsP_IndexPair& TCsP_Typhoon::maxvorcells(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.maxVorCells)
  return _internal_maxvorcells().Get(index);
}
inline ::TCsP_IndexPair* PROTOBUF_NONNULL TCsP_Typhoon::add_maxvorcells()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::TCsP_IndexPair* _add =
      _internal_mutable_maxvorcells()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:TCsP.Typhoon.maxVorCells)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>& TCsP_Typhoon::maxvorcells() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TCsP.Typhoon.maxVorCells)
  return _internal_maxvorcells();
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>&
TCsP_Typhoon::_internal_maxvorcells() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.maxvorcells_;
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_IndexPair>* PROTOBUF_NONNULL
TCsP_Typhoon::_internal_mutable_maxvorcells() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.maxvorcells_;
}

// repeated .TCsP.LatLonPair geoCenters = 2;
inline int TCsP_Typhoon::_internal_geocenters_size() const {
  return _internal_geocenters().size();
}
inline int TCsP_Typhoon::geocenters_size() const {
  return _internal_geocenters_size();
}
inline void TCsP_Typhoon::clear_geocenters() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.geocenters_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::TCsP_LatLonPair* PROTOBUF_NONNULL TCsP_Typhoon::mutable_geocenters(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:TCsP.Typhoon.geoCenters)
  return _internal_mutable_geocenters()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_LatLonPair>* PROTOBUF_NONNULL TCsP_Typhoon::mutable_geocenters()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:TCsP.Typhoon.geoCenters)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_geocenters();
}
inline const ::TCsP_LatLonPair& TCsP_Typhoon::geocenters(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.geoCenters)
  return _internal_geocenters().Get(index);
}
inline ::TCsP_LatLonPair* PROTOBUF_NONNULL TCsP_Typhoon::add_geocenters()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::TCsP_LatLonPair* _add =
      _internal_mutable_geocenters()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:TCsP.Typhoon.geoCenters)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_LatLonPair>& TCsP_Typhoon::geocenters() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TCsP.Typhoon.geoCenters)
  return _internal_geocenters();
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_LatLonPair>&
TCsP_Typhoon::_internal_geocenters() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.geocenters_;
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_LatLonPair>* PROTOBUF_NONNULL
TCsP_Typhoon::_internal_mutable_geocenters() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.geocenters_;
}

// int32 startTimeIndex = 3;
inline void TCsP_Typhoon::clear_starttimeindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.starttimeindex_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t TCsP_Typhoon::starttimeindex() const {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.startTimeIndex)
  return _internal_starttimeindex();
}
inline void TCsP_Typhoon::set_starttimeindex(::int32_t value) {
  _internal_set_starttimeindex(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:TCsP.Typhoon.startTimeIndex)
}
inline ::int32_t TCsP_Typhoon::_internal_starttimeindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.starttimeindex_;
}
inline void TCsP_Typhoon::_internal_set_starttimeindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.starttimeindex_ = value;
}

// int32 endTimeIndex = 4;
inline void TCsP_Typhoon::clear_endtimeindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.endtimeindex_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t TCsP_Typhoon::endtimeindex() const {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.endTimeIndex)
  return _internal_endtimeindex();
}
inline void TCsP_Typhoon::set_endtimeindex(::int32_t value) {
  _internal_set_endtimeindex(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:TCsP.Typhoon.endTimeIndex)
}
inline ::int32_t TCsP_Typhoon::_internal_endtimeindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.endtimeindex_;
}
inline void TCsP_Typhoon::_internal_set_endtimeindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.endtimeindex_ = value;
}

// repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
inline int TCsP_Typhoon::_internal_vorscellsindex_size() const {
  return _internal_vorscellsindex().size();
}
inline int TCsP_Typhoon::vorscellsindex_size() const {
  return _internal_vorscellsindex_size();
}
inline void TCsP_Typhoon::clear_vorscellsindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vorscellsindex_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::TCsP_VorCellsIndex* PROTOBUF_NONNULL TCsP_Typhoon::mutable_vorscellsindex(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:TCsP.Typhoon.vorsCellsIndex)
  return _internal_mutable_vorscellsindex()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_VorCellsIndex>* PROTOBUF_NONNULL TCsP_Typhoon::mutable_vorscellsindex()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:TCsP.Typhoon.vorsCellsIndex)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vorscellsindex();
}
inline const ::TCsP_VorCellsIndex& TCsP_Typhoon::vorscellsindex(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.vorsCellsIndex)
  return _internal_vorscellsindex().Get(index);
}
inline ::TCsP_VorCellsIndex* PROTOBUF_NONNULL TCsP_Typhoon::add_vorscellsindex()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::TCsP_VorCellsIndex* _add =
      _internal_mutable_vorscellsindex()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:TCsP.Typhoon.vorsCellsIndex)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_VorCellsIndex>& TCsP_Typhoon::vorscellsindex() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TCsP.Typhoon.vorsCellsIndex)
  return _internal_vorscellsindex();
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_VorCellsIndex>&
TCsP_Typhoon::_internal_vorscellsindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vorscellsindex_;
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_VorCellsIndex>* PROTOBUF_NONNULL
TCsP_Typhoon::_internal_mutable_vorscellsindex() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vorscellsindex_;
}

// -------------------------------------------------------------------

// TCsP

// repeated .TCsP.Typhoon typhoons = 1;
inline int TCsP::_internal_typhoons_size() const {
  return _internal_typhoons().size();
}
inline int TCsP::typhoons_size() const {
  return _internal_typhoons_size();
}
inline void TCsP::clear_typhoons() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typhoons_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::TCsP_Typhoon* PROTOBUF_NONNULL TCsP::mutable_typhoons(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:TCsP.typhoons)
  return _internal_mutable_typhoons()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_Typhoon>* PROTOBUF_NONNULL TCsP::mutable_typhoons()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:TCsP.typhoons)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_typhoons();
}
inline const ::TCsP_Typhoon& TCsP::typhoons(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TCsP.typhoons)
  return _internal_typhoons().Get(index);
}
inline ::TCsP_Typhoon* PROTOBUF_NONNULL TCsP::add_typhoons()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::TCsP_Typhoon* _add =
      _internal_mutable_typhoons()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:TCsP.typhoons)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_Typhoon>& TCsP::typhoons() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TCsP.typhoons)
  return _internal_typhoons();
}
inline const ::google::protobuf::RepeatedPtrField<::TCsP_Typhoon>&
TCsP::_internal_typhoons() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.typhoons_;
}
inline ::google::protobuf::RepeatedPtrField<::TCsP_Typhoon>* PROTOBUF_NONNULL
TCsP::_internal_mutable_typhoons() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.typhoons_;
}

// string timeUnits = 2;
inline void TCsP::clear_timeunits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeunits_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& TCsP::timeunits() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TCsP.timeUnits)
  return _internal_timeunits();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TCsP::set_timeunits(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.timeunits_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:TCsP.timeUnits)
}
inline ::std::string* PROTOBUF_NONNULL TCsP::mutable_timeunits()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_timeunits();
  // @@protoc_insertion_point(field_mutable:TCsP.timeUnits)
  return _s;
}
inline const ::std::string& TCsP::_internal_timeunits() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timeunits_.Get();
}
inline void TCsP::_internal_set_timeunits(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeunits_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TCsP::_internal_mutable_timeunits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.timeunits_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TCsP::release_timeunits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:TCsP.timeUnits)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.timeunits_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.timeunits_.Set("", GetArena());
  }
  return released;
}
inline void TCsP::set_allocated_timeunits(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.timeunits_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.timeunits_.IsDefault()) {
    _impl_.timeunits_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:TCsP.timeUnits)
}

// bool time_noleap = 3;
inline void TCsP::clear_time_noleap() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_noleap_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool TCsP::time_noleap() const {
  // @@protoc_insertion_point(field_get:TCsP.time_noleap)
  return _internal_time_noleap();
}
inline void TCsP::set_time_noleap(bool value) {
  _internal_set_time_noleap(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:TCsP.time_noleap)
}
inline bool TCsP::_internal_time_noleap() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_noleap_;
}
inline void TCsP::_internal_set_time_noleap(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_noleap_ = value;
}

// int32 firstTimeValue = 4;
inline void TCsP::clear_firsttimevalue() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.firsttimevalue_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t TCsP::firsttimevalue() const {
  // @@protoc_insertion_point(field_get:TCsP.firstTimeValue)
  return _internal_firsttimevalue();
}
inline void TCsP::set_firsttimevalue(::int32_t value) {
  _internal_set_firsttimevalue(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:TCsP.firstTimeValue)
}
inline ::int32_t TCsP::_internal_firsttimevalue() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.firsttimevalue_;
}
inline void TCsP::_internal_set_firsttimevalue(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.firsttimevalue_ = value;
}

// int32 timeHourInterval = 5;
inline void TCsP::clear_timehourinterval() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timehourinterval_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t TCsP::timehourinterval() const {
  // @@protoc_insertion_point(field_get:TCsP.timeHourInterval)
  return _internal_timehourinterval();
}
inline void TCsP::set_timehourinterval(::int32_t value) {
  _internal_set_timehourinterval(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:TCsP.timeHourInterval)
}
inline ::int32_t TCsP::_internal_timehourinterval() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timehourinterval_;
}
inline void TCsP::_internal_set_timehourinterval(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timehourinterval_ = value;
}

// repeated float lats = 6;
inline int TCsP::_internal_lats_size() const {
  return _internal_lats().size();
}
inline int TCsP::lats_size() const {
  return _internal_lats_size();
}
inline void TCsP::clear_lats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lats_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline float TCsP::lats(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.lats)
  return _internal_lats().Get(index);
}
inline void TCsP::set_lats(int index, float value) {
  _internal_mutable_lats()->Set(index, value);
  // @@protoc_insertion_point(field_set:TCsP.lats)
}
inline void TCsP::add_lats(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_lats()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:TCsP.lats)
}
inline const ::google::protobuf::RepeatedField<float>& TCsP::lats() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TCsP.lats)
  return _internal_lats();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL TCsP::mutable_lats()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:TCsP.lats)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_lats();
}
inline const ::google::protobuf::RepeatedField<float>&
TCsP::_internal_lats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lats_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
TCsP::_internal_mutable_lats() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.lats_;
}

// repeated float lons = 7;
inline int TCsP::_internal_lons_size() const {
  return _internal_lons().size();
}
inline int TCsP::lons_size() const {
  return _internal_lons_size();
}
inline void TCsP::clear_lons() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lons_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline float TCsP::lons(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.lons)
  return _internal_lons().Get(index);
}
inline void TCsP::set_lons(int index, float value) {
  _internal_mutable_lons()->Set(index, value);
  // @@protoc_insertion_point(field_set:TCsP.lons)
}
inline void TCsP::add_lons(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_lons()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:TCsP.lons)
}
inline const ::google::protobuf::RepeatedField<float>& TCsP::lons() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TCsP.lons)
  return _internal_lons();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL TCsP::mutable_lons()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:TCsP.lons)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_lons();
}
inline const ::google::protobuf::RepeatedField<float>&
TCsP::_internal_lons() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lons_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
TCsP::_internal_mutable_lons() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.lons_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // TCsP_2eproto_2epb_2eh
