// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TCsP.proto
// Protobuf C++ Version: 6.33.4

#include "TCsP.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr TCsP_LatLonPair::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        lat_{0},
        lon_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TCsP_LatLonPair::TCsP_LatLonPair(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TCsP_LatLonPair_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TCsP_LatLonPairDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsP_LatLonPairDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsP_LatLonPairDefaultTypeInternal() {}
  union {
    TCsP_LatLonPair _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsP_LatLonPairDefaultTypeInternal _TCsP_LatLonPair_default_instance_;

inline constexpr TCsP_IndexPair::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        latindex_{0},
        lonindex_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TCsP_IndexPair::TCsP_IndexPair(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TCsP_IndexPair_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TCsP_IndexPairDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsP_IndexPairDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsP_IndexPairDefaultTypeInternal() {}
  union {
    TCsP_IndexPair _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsP_IndexPairDefaultTypeInternal _TCsP_IndexPair_default_instance_;

inline constexpr TCsP_VorCellsIndex::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        vorcellsindex_{} {}

template <typename>
PROTOBUF_CONSTEXPR TCsP_VorCellsIndex::TCsP_VorCellsIndex(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TCsP_VorCellsIndex_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TCsP_VorCellsIndexDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsP_VorCellsIndexDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsP_VorCellsIndexDefaultTypeInternal() {}
  union {
    TCsP_VorCellsIndex _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsP_VorCellsIndexDefaultTypeInternal _TCsP_VorCellsIndex_default_instance_;

inline constexpr TCsP_Typhoon::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        maxvorcells_{},
        geocenters_{},
        vorscellsindex_{},
        starttimeindex_{0},
        endtimeindex_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TCsP_Typhoon::TCsP_Typhoon(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TCsP_Typhoon_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TCsP_TyphoonDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsP_TyphoonDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsP_TyphoonDefaultTypeInternal() {}
  union {
    TCsP_Typhoon _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsP_TyphoonDefaultTypeInternal _TCsP_Typhoon_default_instance_;

inline constexpr TCsP::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        typhoons_{},
        lats_{},
        lons_{},
        timeunits_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        time_noleap_{false},
        firsttimevalue_{0},
        timehourinterval_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TCsP::TCsP(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TCsP_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TCsPDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCsPDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCsPDefaultTypeInternal() {}
  union {
    TCsP _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCsPDefaultTypeInternal _TCsP_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_TCsP_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_TCsP_2eproto = nullptr;
const ::uint32_t
    TableStruct_TCsP_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::TCsP_IndexPair, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::TCsP_IndexPair, _impl_.latindex_),
        PROTOBUF_FIELD_OFFSET(::TCsP_IndexPair, _impl_.lonindex_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::TCsP_LatLonPair, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::TCsP_LatLonPair, _impl_.lat_),
        PROTOBUF_FIELD_OFFSET(::TCsP_LatLonPair, _impl_.lon_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::TCsP_VorCellsIndex, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::TCsP_VorCellsIndex, _impl_.vorcellsindex_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.maxvorcells_),
        PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.geocenters_),
        PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.starttimeindex_),
        PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.endtimeindex_),
        PROTOBUF_FIELD_OFFSET(::TCsP_Typhoon, _impl_.vorscellsindex_),
        0,
        1,
        3,
        4,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::TCsP, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.typhoons_),
        PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.timeunits_),
        PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.time_noleap_),
        PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.firsttimevalue_),
        PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.timehourinterval_),
        PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.lats_),
        PROTOBUF_FIELD_OFFSET(::TCsP, _impl_.lons_),
        0,
        3,
        4,
        5,
        6,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::TCsP_IndexPair)},
        {7, sizeof(::TCsP_LatLonPair)},
        {14, sizeof(::TCsP_VorCellsIndex)},
        {19, sizeof(::TCsP_Typhoon)},
        {32, sizeof(::TCsP)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_TCsP_IndexPair_default_instance_._instance,
    &::_TCsP_LatLonPair_default_instance_._instance,
    &::_TCsP_VorCellsIndex_default_instance_._instance,
    &::_TCsP_Typhoon_default_instance_._instance,
    &::_TCsP_default_instance_._instance,
};
const char descriptor_table_protodef_TCsP_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nTCsP.proto\"\342\003\n\004TCsP\022\037\n\010typhoons\030\001 \003(\0132"
    "\r.TCsP.Typhoon\022\021\n\ttimeUnits\030\002 \001(\t\022\023\n\013tim"
    "e_noleap\030\003 \001(\010\022\026\n\016firstTimeValue\030\004 \001(\005\022\030"
    "\n\020timeHourInterval\030\005 \001(\005\022\014\n\004lats\030\006 \003(\002\022\014"
    "\n\004lons\030\007 \003(\002\032/\n\tIndexPair\022\020\n\010latIndex\030\001 "
    "\001(\005\022\020\n\010lonIndex\030\002 \001(\005\032&\n\nLatLonPair\022\013\n\003l"
    "at\030\001 \001(\002\022\013\n\003lon\030\002 \001(\002\0327\n\rVorCellsIndex\022&"
    "\n\rvorCellsIndex\030\001 \003(\0132\017.TCsP.IndexPair\032\260"
    "\001\n\007Typhoon\022$\n\013maxVorCells\030\001 \003(\0132\017.TCsP.I"
    "ndexPair\022$\n\ngeoCenters\030\002 \003(\0132\020.TCsP.LatL"
    "onPair\022\026\n\016startTimeIndex\030\003 \001(\005\022\024\n\014endTim"
    "eIndex\030\004 \001(\005\022+\n\016vorsCellsIndex\030\005 \003(\0132\023.T"
    "CsP.VorCellsIndexb\006proto3"
};
static ::absl::once_flag descriptor_table_TCsP_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_TCsP_2eproto = {
    false,
    false,
    505,
    descriptor_table_protodef_TCsP_2eproto,
    "TCsP.proto",
    &descriptor_table_TCsP_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_TCsP_2eproto::offsets,
    file_level_enum_descriptors_TCsP_2eproto,
    file_level_service_descriptors_TCsP_2eproto,
};
// ===================================================================

class TCsP_IndexPair::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TCsP_IndexPair>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_._has_bits_);
};

TCsP_IndexPair::TCsP_IndexPair(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_IndexPair_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TCsP.IndexPair)
}
TCsP_IndexPair::TCsP_IndexPair(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TCsP_IndexPair& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_IndexPair_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE TCsP_IndexPair::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void TCsP_IndexPair::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, latindex_),
           0,
           offsetof(Impl_, lonindex_) -
               offsetof(Impl_, latindex_) +
               sizeof(Impl_::lonindex_));
}
TCsP_IndexPair::~TCsP_IndexPair() {
  // @@protoc_insertion_point(destructor:TCsP.IndexPair)
  SharedDtor(*this);
}
inline void TCsP_IndexPair::SharedDtor(MessageLite& self) {
  TCsP_IndexPair& this_ = static_cast<TCsP_IndexPair&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TCsP_IndexPair::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TCsP_IndexPair(arena);
}
constexpr auto TCsP_IndexPair::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TCsP_IndexPair),
                                            alignof(TCsP_IndexPair));
}
constexpr auto TCsP_IndexPair::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TCsP_IndexPair_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TCsP_IndexPair::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TCsP_IndexPair>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TCsP_IndexPair::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TCsP_IndexPair>(), &TCsP_IndexPair::ByteSizeLong,
              &TCsP_IndexPair::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_._cached_size_),
          false,
      },
      &TCsP_IndexPair::kDescriptorMethods,
      &descriptor_table_TCsP_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TCsP_IndexPair_class_data_ =
        TCsP_IndexPair::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TCsP_IndexPair::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TCsP_IndexPair_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TCsP_IndexPair_class_data_.tc_table);
  return TCsP_IndexPair_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
TCsP_IndexPair::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TCsP_IndexPair_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TCsP_IndexPair>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 lonIndex = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TCsP_IndexPair, _impl_.lonindex_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_.lonindex_)}},
    // int32 latIndex = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TCsP_IndexPair, _impl_.latindex_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_.latindex_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 latIndex = 1;
    {PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_.latindex_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 lonIndex = 2;
    {PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_.lonindex_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void TCsP_IndexPair::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP.IndexPair)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.latindex_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.lonindex_) -
        reinterpret_cast<char*>(&_impl_.latindex_)) + sizeof(_impl_.lonindex_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TCsP_IndexPair::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TCsP_IndexPair& this_ = static_cast<const TCsP_IndexPair&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TCsP_IndexPair::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TCsP_IndexPair& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:TCsP.IndexPair)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 latIndex = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_latindex() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_latindex(), target);
    }
  }

  // int32 lonIndex = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_lonindex() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_lonindex(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP.IndexPair)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TCsP_IndexPair::ByteSizeLong(const MessageLite& base) {
  const TCsP_IndexPair& this_ = static_cast<const TCsP_IndexPair&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TCsP_IndexPair::ByteSizeLong() const {
  const TCsP_IndexPair& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:TCsP.IndexPair)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // int32 latIndex = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_latindex() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_latindex());
      }
    }
    // int32 lonIndex = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_lonindex() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_lonindex());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TCsP_IndexPair::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TCsP_IndexPair*>(&to_msg);
  auto& from = static_cast<const TCsP_IndexPair&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP.IndexPair)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_latindex() != 0) {
        _this->_impl_.latindex_ = from._impl_.latindex_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_lonindex() != 0) {
        _this->_impl_.lonindex_ = from._impl_.lonindex_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TCsP_IndexPair::CopyFrom(const TCsP_IndexPair& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:TCsP.IndexPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TCsP_IndexPair::InternalSwap(TCsP_IndexPair* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_.lonindex_)
      + sizeof(TCsP_IndexPair::_impl_.lonindex_)
      - PROTOBUF_FIELD_OFFSET(TCsP_IndexPair, _impl_.latindex_)>(
          reinterpret_cast<char*>(&_impl_.latindex_),
          reinterpret_cast<char*>(&other->_impl_.latindex_));
}

::google::protobuf::Metadata TCsP_IndexPair::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TCsP_LatLonPair::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TCsP_LatLonPair>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_._has_bits_);
};

TCsP_LatLonPair::TCsP_LatLonPair(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_LatLonPair_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TCsP.LatLonPair)
}
TCsP_LatLonPair::TCsP_LatLonPair(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TCsP_LatLonPair& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_LatLonPair_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE TCsP_LatLonPair::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void TCsP_LatLonPair::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, lat_),
           0,
           offsetof(Impl_, lon_) -
               offsetof(Impl_, lat_) +
               sizeof(Impl_::lon_));
}
TCsP_LatLonPair::~TCsP_LatLonPair() {
  // @@protoc_insertion_point(destructor:TCsP.LatLonPair)
  SharedDtor(*this);
}
inline void TCsP_LatLonPair::SharedDtor(MessageLite& self) {
  TCsP_LatLonPair& this_ = static_cast<TCsP_LatLonPair&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TCsP_LatLonPair::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TCsP_LatLonPair(arena);
}
constexpr auto TCsP_LatLonPair::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TCsP_LatLonPair),
                                            alignof(TCsP_LatLonPair));
}
constexpr auto TCsP_LatLonPair::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TCsP_LatLonPair_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TCsP_LatLonPair::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TCsP_LatLonPair>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TCsP_LatLonPair::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TCsP_LatLonPair>(), &TCsP_LatLonPair::ByteSizeLong,
              &TCsP_LatLonPair::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_._cached_size_),
          false,
      },
      &TCsP_LatLonPair::kDescriptorMethods,
      &descriptor_table_TCsP_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TCsP_LatLonPair_class_data_ =
        TCsP_LatLonPair::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TCsP_LatLonPair::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TCsP_LatLonPair_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TCsP_LatLonPair_class_data_.tc_table);
  return TCsP_LatLonPair_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
TCsP_LatLonPair::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TCsP_LatLonPair_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TCsP_LatLonPair>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float lon = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0,
      PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_.lon_)}},
    // float lat = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0,
      PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_.lat_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float lat = 1;
    {PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_.lat_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float lon = 2;
    {PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_.lon_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void TCsP_LatLonPair::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP.LatLonPair)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.lat_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.lon_) -
        reinterpret_cast<char*>(&_impl_.lat_)) + sizeof(_impl_.lon_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TCsP_LatLonPair::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TCsP_LatLonPair& this_ = static_cast<const TCsP_LatLonPair&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TCsP_LatLonPair::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TCsP_LatLonPair& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:TCsP.LatLonPair)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // float lat = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_lat()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          1, this_._internal_lat(), target);
    }
  }

  // float lon = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_lon()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_lon(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP.LatLonPair)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TCsP_LatLonPair::ByteSizeLong(const MessageLite& base) {
  const TCsP_LatLonPair& this_ = static_cast<const TCsP_LatLonPair&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TCsP_LatLonPair::ByteSizeLong() const {
  const TCsP_LatLonPair& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:TCsP.LatLonPair)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // float lat = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_lat()) != 0) {
        total_size += 5;
      }
    }
    // float lon = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_lon()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TCsP_LatLonPair::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TCsP_LatLonPair*>(&to_msg);
  auto& from = static_cast<const TCsP_LatLonPair&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP.LatLonPair)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_lat()) != 0) {
        _this->_impl_.lat_ = from._impl_.lat_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_lon()) != 0) {
        _this->_impl_.lon_ = from._impl_.lon_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TCsP_LatLonPair::CopyFrom(const TCsP_LatLonPair& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:TCsP.LatLonPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TCsP_LatLonPair::InternalSwap(TCsP_LatLonPair* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_.lon_)
      + sizeof(TCsP_LatLonPair::_impl_.lon_)
      - PROTOBUF_FIELD_OFFSET(TCsP_LatLonPair, _impl_.lat_)>(
          reinterpret_cast<char*>(&_impl_.lat_),
          reinterpret_cast<char*>(&other->_impl_.lat_));
}

::google::protobuf::Metadata TCsP_LatLonPair::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TCsP_VorCellsIndex::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TCsP_VorCellsIndex>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TCsP_VorCellsIndex, _impl_._has_bits_);
};

TCsP_VorCellsIndex::TCsP_VorCellsIndex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_VorCellsIndex_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TCsP.VorCellsIndex)
}
PROTOBUF_NDEBUG_INLINE TCsP_VorCellsIndex::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::TCsP_VorCellsIndex& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        vorcellsindex_{visibility, arena, from.vorcellsindex_} {}

TCsP_VorCellsIndex::TCsP_VorCellsIndex(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TCsP_VorCellsIndex& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_VorCellsIndex_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TCsP_VorCellsIndex* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:TCsP.VorCellsIndex)
}
PROTOBUF_NDEBUG_INLINE TCsP_VorCellsIndex::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        vorcellsindex_{visibility, arena} {}

inline void TCsP_VorCellsIndex::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TCsP_VorCellsIndex::~TCsP_VorCellsIndex() {
  // @@protoc_insertion_point(destructor:TCsP.VorCellsIndex)
  SharedDtor(*this);
}
inline void TCsP_VorCellsIndex::SharedDtor(MessageLite& self) {
  TCsP_VorCellsIndex& this_ = static_cast<TCsP_VorCellsIndex&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TCsP_VorCellsIndex::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TCsP_VorCellsIndex(arena);
}
constexpr auto TCsP_VorCellsIndex::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TCsP_VorCellsIndex, _impl_.vorcellsindex_) +
          decltype(TCsP_VorCellsIndex::_impl_.vorcellsindex_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(TCsP_VorCellsIndex), alignof(TCsP_VorCellsIndex), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TCsP_VorCellsIndex::PlacementNew_,
                                 sizeof(TCsP_VorCellsIndex),
                                 alignof(TCsP_VorCellsIndex));
  }
}
constexpr auto TCsP_VorCellsIndex::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TCsP_VorCellsIndex_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TCsP_VorCellsIndex::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TCsP_VorCellsIndex>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TCsP_VorCellsIndex::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TCsP_VorCellsIndex>(), &TCsP_VorCellsIndex::ByteSizeLong,
              &TCsP_VorCellsIndex::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TCsP_VorCellsIndex, _impl_._cached_size_),
          false,
      },
      &TCsP_VorCellsIndex::kDescriptorMethods,
      &descriptor_table_TCsP_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TCsP_VorCellsIndex_class_data_ =
        TCsP_VorCellsIndex::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TCsP_VorCellsIndex::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TCsP_VorCellsIndex_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TCsP_VorCellsIndex_class_data_.tc_table);
  return TCsP_VorCellsIndex_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
TCsP_VorCellsIndex::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TCsP_VorCellsIndex, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    TCsP_VorCellsIndex_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TCsP_VorCellsIndex>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .TCsP.IndexPair vorCellsIndex = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(TCsP_VorCellsIndex, _impl_.vorcellsindex_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .TCsP.IndexPair vorCellsIndex = 1;
    {PROTOBUF_FIELD_OFFSET(TCsP_VorCellsIndex, _impl_.vorcellsindex_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::TCsP_IndexPair>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void TCsP_VorCellsIndex::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP.VorCellsIndex)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.vorcellsindex_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TCsP_VorCellsIndex::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TCsP_VorCellsIndex& this_ = static_cast<const TCsP_VorCellsIndex&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TCsP_VorCellsIndex::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TCsP_VorCellsIndex& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:TCsP.VorCellsIndex)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .TCsP.IndexPair vorCellsIndex = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_vorcellsindex_size());
         i < n; i++) {
      const auto& repfield = this_._internal_vorcellsindex().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP.VorCellsIndex)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TCsP_VorCellsIndex::ByteSizeLong(const MessageLite& base) {
  const TCsP_VorCellsIndex& this_ = static_cast<const TCsP_VorCellsIndex&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TCsP_VorCellsIndex::ByteSizeLong() const {
  const TCsP_VorCellsIndex& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:TCsP.VorCellsIndex)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .TCsP.IndexPair vorCellsIndex = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_vorcellsindex_size();
      for (const auto& msg : this_._internal_vorcellsindex()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TCsP_VorCellsIndex::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TCsP_VorCellsIndex*>(&to_msg);
  auto& from = static_cast<const TCsP_VorCellsIndex&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP.VorCellsIndex)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_vorcellsindex()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_vorcellsindex());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TCsP_VorCellsIndex::CopyFrom(const TCsP_VorCellsIndex& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:TCsP.VorCellsIndex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TCsP_VorCellsIndex::InternalSwap(TCsP_VorCellsIndex* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.vorcellsindex_.InternalSwap(&other->_impl_.vorcellsindex_);
}

::google::protobuf::Metadata TCsP_VorCellsIndex::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TCsP_Typhoon::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TCsP_Typhoon>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_._has_bits_);
};

TCsP_Typhoon::TCsP_Typhoon(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_Typhoon_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TCsP.Typhoon)
}
PROTOBUF_NDEBUG_INLINE TCsP_Typhoon::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::TCsP_Typhoon& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        maxvorcells_{visibility, arena, from.maxvorcells_},
        geocenters_{visibility, arena, from.geocenters_},
        vorscellsindex_{visibility, arena, from.vorscellsindex_} {}

TCsP_Typhoon::TCsP_Typhoon(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TCsP_Typhoon& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_Typhoon_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TCsP_Typhoon* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, starttimeindex_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, starttimeindex_),
           offsetof(Impl_, endtimeindex_) -
               offsetof(Impl_, starttimeindex_) +
               sizeof(Impl_::endtimeindex_));

  // @@protoc_insertion_point(copy_constructor:TCsP.Typhoon)
}
PROTOBUF_NDEBUG_INLINE TCsP_Typhoon::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        maxvorcells_{visibility, arena},
        geocenters_{visibility, arena},
        vorscellsindex_{visibility, arena} {}

inline void TCsP_Typhoon::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, starttimeindex_),
           0,
           offsetof(Impl_, endtimeindex_) -
               offsetof(Impl_, starttimeindex_) +
               sizeof(Impl_::endtimeindex_));
}
TCsP_Typhoon::~TCsP_Typhoon() {
  // @@protoc_insertion_point(destructor:TCsP.Typhoon)
  SharedDtor(*this);
}
inline void TCsP_Typhoon::SharedDtor(MessageLite& self) {
  TCsP_Typhoon& this_ = static_cast<TCsP_Typhoon&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TCsP_Typhoon::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TCsP_Typhoon(arena);
}
constexpr auto TCsP_Typhoon::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.maxvorcells_) +
          decltype(TCsP_Typhoon::_impl_.maxvorcells_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.geocenters_) +
          decltype(TCsP_Typhoon::_impl_.geocenters_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.vorscellsindex_) +
          decltype(TCsP_Typhoon::_impl_.vorscellsindex_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(TCsP_Typhoon), alignof(TCsP_Typhoon), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TCsP_Typhoon::PlacementNew_,
                                 sizeof(TCsP_Typhoon),
                                 alignof(TCsP_Typhoon));
  }
}
constexpr auto TCsP_Typhoon::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TCsP_Typhoon_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TCsP_Typhoon::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TCsP_Typhoon>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TCsP_Typhoon::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TCsP_Typhoon>(), &TCsP_Typhoon::ByteSizeLong,
              &TCsP_Typhoon::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_._cached_size_),
          false,
      },
      &TCsP_Typhoon::kDescriptorMethods,
      &descriptor_table_TCsP_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TCsP_Typhoon_class_data_ =
        TCsP_Typhoon::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TCsP_Typhoon::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TCsP_Typhoon_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TCsP_Typhoon_class_data_.tc_table);
  return TCsP_Typhoon_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 3, 0, 2>
TCsP_Typhoon::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    TCsP_Typhoon_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TCsP_Typhoon>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .TCsP.IndexPair maxVorCells = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.maxvorcells_)}},
    // repeated .TCsP.LatLonPair geoCenters = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.geocenters_)}},
    // int32 startTimeIndex = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TCsP_Typhoon, _impl_.starttimeindex_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.starttimeindex_)}},
    // int32 endTimeIndex = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TCsP_Typhoon, _impl_.endtimeindex_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.endtimeindex_)}},
    // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 2, 2,
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.vorscellsindex_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .TCsP.IndexPair maxVorCells = 1;
    {PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.maxvorcells_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .TCsP.LatLonPair geoCenters = 2;
    {PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.geocenters_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 startTimeIndex = 3;
    {PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.starttimeindex_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 endTimeIndex = 4;
    {PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.endtimeindex_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
    {PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.vorscellsindex_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::TCsP_IndexPair>()},
      {::_pbi::TcParser::GetTable<::TCsP_LatLonPair>()},
      {::_pbi::TcParser::GetTable<::TCsP_VorCellsIndex>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void TCsP_Typhoon::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP.Typhoon)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.maxvorcells_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.geocenters_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.vorscellsindex_.Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    ::memset(&_impl_.starttimeindex_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.endtimeindex_) -
        reinterpret_cast<char*>(&_impl_.starttimeindex_)) + sizeof(_impl_.endtimeindex_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TCsP_Typhoon::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TCsP_Typhoon& this_ = static_cast<const TCsP_Typhoon&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TCsP_Typhoon::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TCsP_Typhoon& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:TCsP.Typhoon)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .TCsP.IndexPair maxVorCells = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_maxvorcells_size());
         i < n; i++) {
      const auto& repfield = this_._internal_maxvorcells().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated .TCsP.LatLonPair geoCenters = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_geocenters_size());
         i < n; i++) {
      const auto& repfield = this_._internal_geocenters().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // int32 startTimeIndex = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_starttimeindex() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_starttimeindex(), target);
    }
  }

  // int32 endTimeIndex = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_endtimeindex() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_endtimeindex(), target);
    }
  }

  // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_vorscellsindex_size());
         i < n; i++) {
      const auto& repfield = this_._internal_vorscellsindex().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              5, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP.Typhoon)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TCsP_Typhoon::ByteSizeLong(const MessageLite& base) {
  const TCsP_Typhoon& this_ = static_cast<const TCsP_Typhoon&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TCsP_Typhoon::ByteSizeLong() const {
  const TCsP_Typhoon& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:TCsP.Typhoon)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated .TCsP.IndexPair maxVorCells = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_maxvorcells_size();
      for (const auto& msg : this_._internal_maxvorcells()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .TCsP.LatLonPair geoCenters = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_geocenters_size();
      for (const auto& msg : this_._internal_geocenters()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      total_size += 1UL * this_._internal_vorscellsindex_size();
      for (const auto& msg : this_._internal_vorscellsindex()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // int32 startTimeIndex = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_starttimeindex() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_starttimeindex());
      }
    }
    // int32 endTimeIndex = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_endtimeindex() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_endtimeindex());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TCsP_Typhoon::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TCsP_Typhoon*>(&to_msg);
  auto& from = static_cast<const TCsP_Typhoon&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP.Typhoon)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_maxvorcells()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_maxvorcells());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_geocenters()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_geocenters());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_vorscellsindex()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_vorscellsindex());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_starttimeindex() != 0) {
        _this->_impl_.starttimeindex_ = from._impl_.starttimeindex_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_endtimeindex() != 0) {
        _this->_impl_.endtimeindex_ = from._impl_.endtimeindex_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TCsP_Typhoon::CopyFrom(const TCsP_Typhoon& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:TCsP.Typhoon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TCsP_Typhoon::InternalSwap(TCsP_Typhoon* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.maxvorcells_.InternalSwap(&other->_impl_.maxvorcells_);
  _impl_.geocenters_.InternalSwap(&other->_impl_.geocenters_);
  _impl_.vorscellsindex_.InternalSwap(&other->_impl_.vorscellsindex_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.endtimeindex_)
      + sizeof(TCsP_Typhoon::_impl_.endtimeindex_)
      - PROTOBUF_FIELD_OFFSET(TCsP_Typhoon, _impl_.starttimeindex_)>(
          reinterpret_cast<char*>(&_impl_.starttimeindex_),
          reinterpret_cast<char*>(&other->_impl_.starttimeindex_));
}

::google::protobuf::Metadata TCsP_Typhoon::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TCsP::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TCsP>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TCsP, _impl_._has_bits_);
};

TCsP::TCsP(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TCsP)
}
PROTOBUF_NDEBUG_INLINE TCsP::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::TCsP& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        typhoons_{visibility, arena, from.typhoons_},
        lats_{visibility, arena, from.lats_},
        lons_{visibility, arena, from.lons_},
        timeunits_(arena, from.timeunits_) {}

TCsP::TCsP(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TCsP& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TCsP_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TCsP* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, time_noleap_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, time_noleap_),
           offsetof(Impl_, timehourinterval_) -
               offsetof(Impl_, time_noleap_) +
               sizeof(Impl_::timehourinterval_));

  // @@protoc_insertion_point(copy_constructor:TCsP)
}
PROTOBUF_NDEBUG_INLINE TCsP::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        typhoons_{visibility, arena},
        lats_{visibility, arena},
        lons_{visibility, arena},
        timeunits_(arena) {}

inline void TCsP::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, time_noleap_),
           0,
           offsetof(Impl_, timehourinterval_) -
               offsetof(Impl_, time_noleap_) +
               sizeof(Impl_::timehourinterval_));
}
TCsP::~TCsP() {
  // @@protoc_insertion_point(destructor:TCsP)
  SharedDtor(*this);
}
inline void TCsP::SharedDtor(MessageLite& self) {
  TCsP& this_ = static_cast<TCsP&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.timeunits_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TCsP::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TCsP(arena);
}
constexpr auto TCsP::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.typhoons_) +
          decltype(TCsP::_impl_.typhoons_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.lats_) +
          decltype(TCsP::_impl_.lats_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.lons_) +
          decltype(TCsP::_impl_.lons_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(TCsP), alignof(TCsP), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TCsP::PlacementNew_,
                                 sizeof(TCsP),
                                 alignof(TCsP));
  }
}
constexpr auto TCsP::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TCsP_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TCsP::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TCsP>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TCsP::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TCsP>(), &TCsP::ByteSizeLong,
              &TCsP::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TCsP, _impl_._cached_size_),
          false,
      },
      &TCsP::kDescriptorMethods,
      &descriptor_table_TCsP_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TCsP_class_data_ =
        TCsP::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TCsP::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TCsP_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TCsP_class_data_.tc_table);
  return TCsP_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 1, 22, 2>
TCsP::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TCsP, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    TCsP_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TCsP>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .TCsP.Typhoon typhoons = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.typhoons_)}},
    // string timeUnits = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 3, 0,
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.timeunits_)}},
    // bool time_noleap = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TCsP, _impl_.time_noleap_), 4>(),
     {24, 4, 0,
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.time_noleap_)}},
    // int32 firstTimeValue = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TCsP, _impl_.firsttimevalue_), 5>(),
     {32, 5, 0,
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.firsttimevalue_)}},
    // int32 timeHourInterval = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TCsP, _impl_.timehourinterval_), 6>(),
     {40, 6, 0,
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.timehourinterval_)}},
    // repeated float lats = 6;
    {::_pbi::TcParser::FastF32P1,
     {50, 1, 0,
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.lats_)}},
    // repeated float lons = 7;
    {::_pbi::TcParser::FastF32P1,
     {58, 2, 0,
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.lons_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .TCsP.Typhoon typhoons = 1;
    {PROTOBUF_FIELD_OFFSET(TCsP, _impl_.typhoons_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string timeUnits = 2;
    {PROTOBUF_FIELD_OFFSET(TCsP, _impl_.timeunits_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool time_noleap = 3;
    {PROTOBUF_FIELD_OFFSET(TCsP, _impl_.time_noleap_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // int32 firstTimeValue = 4;
    {PROTOBUF_FIELD_OFFSET(TCsP, _impl_.firsttimevalue_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 timeHourInterval = 5;
    {PROTOBUF_FIELD_OFFSET(TCsP, _impl_.timehourinterval_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated float lats = 6;
    {PROTOBUF_FIELD_OFFSET(TCsP, _impl_.lats_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float lons = 7;
    {PROTOBUF_FIELD_OFFSET(TCsP, _impl_.lons_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::TCsP_Typhoon>()},
  }},
  {{
    "\4\0\11\0\0\0\0\0"
    "TCsP"
    "timeUnits"
  }},
};
PROTOBUF_NOINLINE void TCsP::Clear() {
// @@protoc_insertion_point(message_clear_start:TCsP)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.typhoons_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.lats_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.lons_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.timeunits_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000070U)) {
    ::memset(&_impl_.time_noleap_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.timehourinterval_) -
        reinterpret_cast<char*>(&_impl_.time_noleap_)) + sizeof(_impl_.timehourinterval_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TCsP::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TCsP& this_ = static_cast<const TCsP&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TCsP::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TCsP& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:TCsP)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .TCsP.Typhoon typhoons = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_typhoons_size());
         i < n; i++) {
      const auto& repfield = this_._internal_typhoons().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // string timeUnits = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_timeunits().empty()) {
      const ::std::string& _s = this_._internal_timeunits();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TCsP.timeUnits");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // bool time_noleap = 3;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_time_noleap() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_time_noleap(), target);
    }
  }

  // int32 firstTimeValue = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_firsttimevalue() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_firsttimevalue(), target);
    }
  }

  // int32 timeHourInterval = 5;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_timehourinterval() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_timehourinterval(), target);
    }
  }

  // repeated float lats = 6;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    if (this_._internal_lats_size() > 0) {
      target = stream->WriteFixedPacked(6, this_._internal_lats(), target);
    }
  }

  // repeated float lons = 7;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    if (this_._internal_lons_size() > 0) {
      target = stream->WriteFixedPacked(7, this_._internal_lons(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TCsP)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TCsP::ByteSizeLong(const MessageLite& base) {
  const TCsP& this_ = static_cast<const TCsP&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TCsP::ByteSizeLong() const {
  const TCsP& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:TCsP)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // repeated .TCsP.Typhoon typhoons = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_typhoons_size();
      for (const auto& msg : this_._internal_typhoons()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated float lats = 6;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_lats_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated float lons = 7;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_lons_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // string timeUnits = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_timeunits().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_timeunits());
      }
    }
    // bool time_noleap = 3;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_time_noleap() != 0) {
        total_size += 2;
      }
    }
    // int32 firstTimeValue = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_firsttimevalue() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_firsttimevalue());
      }
    }
    // int32 timeHourInterval = 5;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_timehourinterval() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_timehourinterval());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TCsP::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TCsP*>(&to_msg);
  auto& from = static_cast<const TCsP&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:TCsP)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_typhoons()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_typhoons());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_lats()->MergeFrom(from._internal_lats());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_lons()->MergeFrom(from._internal_lons());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_timeunits().empty()) {
        _this->_internal_set_timeunits(from._internal_timeunits());
      } else {
        if (_this->_impl_.timeunits_.IsDefault()) {
          _this->_internal_set_timeunits("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_time_noleap() != 0) {
        _this->_impl_.time_noleap_ = from._impl_.time_noleap_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_firsttimevalue() != 0) {
        _this->_impl_.firsttimevalue_ = from._impl_.firsttimevalue_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_timehourinterval() != 0) {
        _this->_impl_.timehourinterval_ = from._impl_.timehourinterval_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TCsP::CopyFrom(const TCsP& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:TCsP)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TCsP::InternalSwap(TCsP* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.typhoons_.InternalSwap(&other->_impl_.typhoons_);
  _impl_.lats_.InternalSwap(&other->_impl_.lats_);
  _impl_.lons_.InternalSwap(&other->_impl_.lons_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.timeunits_, &other->_impl_.timeunits_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TCsP, _impl_.timehourinterval_)
      + sizeof(TCsP::_impl_.timehourinterval_)
      - PROTOBUF_FIELD_OFFSET(TCsP, _impl_.time_noleap_)>(
          reinterpret_cast<char*>(&_impl_.time_noleap_),
          reinterpret_cast<char*>(&other->_impl_.time_noleap_));
}

::google::protobuf::Metadata TCsP::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_TCsP_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
