// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TCsP.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TCsP_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TCsP_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TCsP_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TCsP_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TCsP_2eproto;
class TCsP;
struct TCsPDefaultTypeInternal;
extern TCsPDefaultTypeInternal _TCsP_default_instance_;
class TCsP_IndexPair;
struct TCsP_IndexPairDefaultTypeInternal;
extern TCsP_IndexPairDefaultTypeInternal _TCsP_IndexPair_default_instance_;
class TCsP_LatLonPair;
struct TCsP_LatLonPairDefaultTypeInternal;
extern TCsP_LatLonPairDefaultTypeInternal _TCsP_LatLonPair_default_instance_;
class TCsP_Typhoon;
struct TCsP_TyphoonDefaultTypeInternal;
extern TCsP_TyphoonDefaultTypeInternal _TCsP_Typhoon_default_instance_;
class TCsP_VorCellsIndex;
struct TCsP_VorCellsIndexDefaultTypeInternal;
extern TCsP_VorCellsIndexDefaultTypeInternal _TCsP_VorCellsIndex_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::TCsP* Arena::CreateMaybeMessage<::TCsP>(Arena*);
template<> ::TCsP_IndexPair* Arena::CreateMaybeMessage<::TCsP_IndexPair>(Arena*);
template<> ::TCsP_LatLonPair* Arena::CreateMaybeMessage<::TCsP_LatLonPair>(Arena*);
template<> ::TCsP_Typhoon* Arena::CreateMaybeMessage<::TCsP_Typhoon>(Arena*);
template<> ::TCsP_VorCellsIndex* Arena::CreateMaybeMessage<::TCsP_VorCellsIndex>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class TCsP_IndexPair final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TCsP.IndexPair) */ {
 public:
  inline TCsP_IndexPair() : TCsP_IndexPair(nullptr) {}
  ~TCsP_IndexPair() override;
  explicit PROTOBUF_CONSTEXPR TCsP_IndexPair(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TCsP_IndexPair(const TCsP_IndexPair& from);
  TCsP_IndexPair(TCsP_IndexPair&& from) noexcept
    : TCsP_IndexPair() {
    *this = ::std::move(from);
  }

  inline TCsP_IndexPair& operator=(const TCsP_IndexPair& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP_IndexPair& operator=(TCsP_IndexPair&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP_IndexPair& default_instance() {
    return *internal_default_instance();
  }
  static inline const TCsP_IndexPair* internal_default_instance() {
    return reinterpret_cast<const TCsP_IndexPair*>(
               &_TCsP_IndexPair_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TCsP_IndexPair& a, TCsP_IndexPair& b) {
    a.Swap(&b);
  }
  inline void Swap(TCsP_IndexPair* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP_IndexPair* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP_IndexPair* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TCsP_IndexPair>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TCsP_IndexPair& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TCsP_IndexPair& from) {
    TCsP_IndexPair::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TCsP_IndexPair* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TCsP.IndexPair";
  }
  protected:
  explicit TCsP_IndexPair(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatIndexFieldNumber = 1,
    kLonIndexFieldNumber = 2,
  };
  // int32 latIndex = 1;
  void clear_latindex();
  int32_t latindex() const;
  void set_latindex(int32_t value);
  private:
  int32_t _internal_latindex() const;
  void _internal_set_latindex(int32_t value);
  public:

  // int32 lonIndex = 2;
  void clear_lonindex();
  int32_t lonindex() const;
  void set_lonindex(int32_t value);
  private:
  int32_t _internal_lonindex() const;
  void _internal_set_lonindex(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:TCsP.IndexPair)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t latindex_;
    int32_t lonindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};
// -------------------------------------------------------------------

class TCsP_LatLonPair final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TCsP.LatLonPair) */ {
 public:
  inline TCsP_LatLonPair() : TCsP_LatLonPair(nullptr) {}
  ~TCsP_LatLonPair() override;
  explicit PROTOBUF_CONSTEXPR TCsP_LatLonPair(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TCsP_LatLonPair(const TCsP_LatLonPair& from);
  TCsP_LatLonPair(TCsP_LatLonPair&& from) noexcept
    : TCsP_LatLonPair() {
    *this = ::std::move(from);
  }

  inline TCsP_LatLonPair& operator=(const TCsP_LatLonPair& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP_LatLonPair& operator=(TCsP_LatLonPair&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP_LatLonPair& default_instance() {
    return *internal_default_instance();
  }
  static inline const TCsP_LatLonPair* internal_default_instance() {
    return reinterpret_cast<const TCsP_LatLonPair*>(
               &_TCsP_LatLonPair_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TCsP_LatLonPair& a, TCsP_LatLonPair& b) {
    a.Swap(&b);
  }
  inline void Swap(TCsP_LatLonPair* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP_LatLonPair* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP_LatLonPair* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TCsP_LatLonPair>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TCsP_LatLonPair& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TCsP_LatLonPair& from) {
    TCsP_LatLonPair::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TCsP_LatLonPair* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TCsP.LatLonPair";
  }
  protected:
  explicit TCsP_LatLonPair(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatFieldNumber = 1,
    kLonFieldNumber = 2,
  };
  // float lat = 1;
  void clear_lat();
  float lat() const;
  void set_lat(float value);
  private:
  float _internal_lat() const;
  void _internal_set_lat(float value);
  public:

  // float lon = 2;
  void clear_lon();
  float lon() const;
  void set_lon(float value);
  private:
  float _internal_lon() const;
  void _internal_set_lon(float value);
  public:

  // @@protoc_insertion_point(class_scope:TCsP.LatLonPair)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float lat_;
    float lon_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};
// -------------------------------------------------------------------

class TCsP_VorCellsIndex final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TCsP.VorCellsIndex) */ {
 public:
  inline TCsP_VorCellsIndex() : TCsP_VorCellsIndex(nullptr) {}
  ~TCsP_VorCellsIndex() override;
  explicit PROTOBUF_CONSTEXPR TCsP_VorCellsIndex(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TCsP_VorCellsIndex(const TCsP_VorCellsIndex& from);
  TCsP_VorCellsIndex(TCsP_VorCellsIndex&& from) noexcept
    : TCsP_VorCellsIndex() {
    *this = ::std::move(from);
  }

  inline TCsP_VorCellsIndex& operator=(const TCsP_VorCellsIndex& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP_VorCellsIndex& operator=(TCsP_VorCellsIndex&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP_VorCellsIndex& default_instance() {
    return *internal_default_instance();
  }
  static inline const TCsP_VorCellsIndex* internal_default_instance() {
    return reinterpret_cast<const TCsP_VorCellsIndex*>(
               &_TCsP_VorCellsIndex_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TCsP_VorCellsIndex& a, TCsP_VorCellsIndex& b) {
    a.Swap(&b);
  }
  inline void Swap(TCsP_VorCellsIndex* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP_VorCellsIndex* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP_VorCellsIndex* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TCsP_VorCellsIndex>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TCsP_VorCellsIndex& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TCsP_VorCellsIndex& from) {
    TCsP_VorCellsIndex::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TCsP_VorCellsIndex* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TCsP.VorCellsIndex";
  }
  protected:
  explicit TCsP_VorCellsIndex(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVorCellsIndexFieldNumber = 1,
  };
  // repeated .TCsP.IndexPair vorCellsIndex = 1;
  int vorcellsindex_size() const;
  private:
  int _internal_vorcellsindex_size() const;
  public:
  void clear_vorcellsindex();
  ::TCsP_IndexPair* mutable_vorcellsindex(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair >*
      mutable_vorcellsindex();
  private:
  const ::TCsP_IndexPair& _internal_vorcellsindex(int index) const;
  ::TCsP_IndexPair* _internal_add_vorcellsindex();
  public:
  const ::TCsP_IndexPair& vorcellsindex(int index) const;
  ::TCsP_IndexPair* add_vorcellsindex();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair >&
      vorcellsindex() const;

  // @@protoc_insertion_point(class_scope:TCsP.VorCellsIndex)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair > vorcellsindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};
// -------------------------------------------------------------------

class TCsP_Typhoon final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TCsP.Typhoon) */ {
 public:
  inline TCsP_Typhoon() : TCsP_Typhoon(nullptr) {}
  ~TCsP_Typhoon() override;
  explicit PROTOBUF_CONSTEXPR TCsP_Typhoon(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TCsP_Typhoon(const TCsP_Typhoon& from);
  TCsP_Typhoon(TCsP_Typhoon&& from) noexcept
    : TCsP_Typhoon() {
    *this = ::std::move(from);
  }

  inline TCsP_Typhoon& operator=(const TCsP_Typhoon& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP_Typhoon& operator=(TCsP_Typhoon&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP_Typhoon& default_instance() {
    return *internal_default_instance();
  }
  static inline const TCsP_Typhoon* internal_default_instance() {
    return reinterpret_cast<const TCsP_Typhoon*>(
               &_TCsP_Typhoon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TCsP_Typhoon& a, TCsP_Typhoon& b) {
    a.Swap(&b);
  }
  inline void Swap(TCsP_Typhoon* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP_Typhoon* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP_Typhoon* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TCsP_Typhoon>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TCsP_Typhoon& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TCsP_Typhoon& from) {
    TCsP_Typhoon::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TCsP_Typhoon* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TCsP.Typhoon";
  }
  protected:
  explicit TCsP_Typhoon(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMaxVorCellsFieldNumber = 1,
    kGeoCentersFieldNumber = 2,
    kVorsCellsIndexFieldNumber = 5,
    kStartTimeIndexFieldNumber = 3,
    kEndTimeIndexFieldNumber = 4,
  };
  // repeated .TCsP.IndexPair maxVorCells = 1;
  int maxvorcells_size() const;
  private:
  int _internal_maxvorcells_size() const;
  public:
  void clear_maxvorcells();
  ::TCsP_IndexPair* mutable_maxvorcells(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair >*
      mutable_maxvorcells();
  private:
  const ::TCsP_IndexPair& _internal_maxvorcells(int index) const;
  ::TCsP_IndexPair* _internal_add_maxvorcells();
  public:
  const ::TCsP_IndexPair& maxvorcells(int index) const;
  ::TCsP_IndexPair* add_maxvorcells();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair >&
      maxvorcells() const;

  // repeated .TCsP.LatLonPair geoCenters = 2;
  int geocenters_size() const;
  private:
  int _internal_geocenters_size() const;
  public:
  void clear_geocenters();
  ::TCsP_LatLonPair* mutable_geocenters(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_LatLonPair >*
      mutable_geocenters();
  private:
  const ::TCsP_LatLonPair& _internal_geocenters(int index) const;
  ::TCsP_LatLonPair* _internal_add_geocenters();
  public:
  const ::TCsP_LatLonPair& geocenters(int index) const;
  ::TCsP_LatLonPair* add_geocenters();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_LatLonPair >&
      geocenters() const;

  // repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
  int vorscellsindex_size() const;
  private:
  int _internal_vorscellsindex_size() const;
  public:
  void clear_vorscellsindex();
  ::TCsP_VorCellsIndex* mutable_vorscellsindex(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_VorCellsIndex >*
      mutable_vorscellsindex();
  private:
  const ::TCsP_VorCellsIndex& _internal_vorscellsindex(int index) const;
  ::TCsP_VorCellsIndex* _internal_add_vorscellsindex();
  public:
  const ::TCsP_VorCellsIndex& vorscellsindex(int index) const;
  ::TCsP_VorCellsIndex* add_vorscellsindex();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_VorCellsIndex >&
      vorscellsindex() const;

  // int32 startTimeIndex = 3;
  void clear_starttimeindex();
  int32_t starttimeindex() const;
  void set_starttimeindex(int32_t value);
  private:
  int32_t _internal_starttimeindex() const;
  void _internal_set_starttimeindex(int32_t value);
  public:

  // int32 endTimeIndex = 4;
  void clear_endtimeindex();
  int32_t endtimeindex() const;
  void set_endtimeindex(int32_t value);
  private:
  int32_t _internal_endtimeindex() const;
  void _internal_set_endtimeindex(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:TCsP.Typhoon)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair > maxvorcells_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_LatLonPair > geocenters_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_VorCellsIndex > vorscellsindex_;
    int32_t starttimeindex_;
    int32_t endtimeindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};
// -------------------------------------------------------------------

class TCsP final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TCsP) */ {
 public:
  inline TCsP() : TCsP(nullptr) {}
  ~TCsP() override;
  explicit PROTOBUF_CONSTEXPR TCsP(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TCsP(const TCsP& from);
  TCsP(TCsP&& from) noexcept
    : TCsP() {
    *this = ::std::move(from);
  }

  inline TCsP& operator=(const TCsP& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCsP& operator=(TCsP&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCsP& default_instance() {
    return *internal_default_instance();
  }
  static inline const TCsP* internal_default_instance() {
    return reinterpret_cast<const TCsP*>(
               &_TCsP_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(TCsP& a, TCsP& b) {
    a.Swap(&b);
  }
  inline void Swap(TCsP* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCsP* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCsP* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TCsP>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TCsP& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TCsP& from) {
    TCsP::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TCsP* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TCsP";
  }
  protected:
  explicit TCsP(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef TCsP_IndexPair IndexPair;
  typedef TCsP_LatLonPair LatLonPair;
  typedef TCsP_VorCellsIndex VorCellsIndex;
  typedef TCsP_Typhoon Typhoon;

  // accessors -------------------------------------------------------

  enum : int {
    kTyphoonsFieldNumber = 1,
    kLatsFieldNumber = 6,
    kLonsFieldNumber = 7,
    kTimeUnitsFieldNumber = 2,
    kTimeNoleapFieldNumber = 3,
    kFirstTimeValueFieldNumber = 4,
    kTimeHourIntervalFieldNumber = 5,
  };
  // repeated .TCsP.Typhoon typhoons = 1;
  int typhoons_size() const;
  private:
  int _internal_typhoons_size() const;
  public:
  void clear_typhoons();
  ::TCsP_Typhoon* mutable_typhoons(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_Typhoon >*
      mutable_typhoons();
  private:
  const ::TCsP_Typhoon& _internal_typhoons(int index) const;
  ::TCsP_Typhoon* _internal_add_typhoons();
  public:
  const ::TCsP_Typhoon& typhoons(int index) const;
  ::TCsP_Typhoon* add_typhoons();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_Typhoon >&
      typhoons() const;

  // repeated float lats = 6;
  int lats_size() const;
  private:
  int _internal_lats_size() const;
  public:
  void clear_lats();
  private:
  float _internal_lats(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_lats() const;
  void _internal_add_lats(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_lats();
  public:
  float lats(int index) const;
  void set_lats(int index, float value);
  void add_lats(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      lats() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_lats();

  // repeated float lons = 7;
  int lons_size() const;
  private:
  int _internal_lons_size() const;
  public:
  void clear_lons();
  private:
  float _internal_lons(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_lons() const;
  void _internal_add_lons(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_lons();
  public:
  float lons(int index) const;
  void set_lons(int index, float value);
  void add_lons(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      lons() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_lons();

  // string timeUnits = 2;
  void clear_timeunits();
  const std::string& timeunits() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timeunits(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timeunits();
  PROTOBUF_NODISCARD std::string* release_timeunits();
  void set_allocated_timeunits(std::string* timeunits);
  private:
  const std::string& _internal_timeunits() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timeunits(const std::string& value);
  std::string* _internal_mutable_timeunits();
  public:

  // bool time_noleap = 3;
  void clear_time_noleap();
  bool time_noleap() const;
  void set_time_noleap(bool value);
  private:
  bool _internal_time_noleap() const;
  void _internal_set_time_noleap(bool value);
  public:

  // int32 firstTimeValue = 4;
  void clear_firsttimevalue();
  int32_t firsttimevalue() const;
  void set_firsttimevalue(int32_t value);
  private:
  int32_t _internal_firsttimevalue() const;
  void _internal_set_firsttimevalue(int32_t value);
  public:

  // int32 timeHourInterval = 5;
  void clear_timehourinterval();
  int32_t timehourinterval() const;
  void set_timehourinterval(int32_t value);
  private:
  int32_t _internal_timehourinterval() const;
  void _internal_set_timehourinterval(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:TCsP)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_Typhoon > typhoons_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > lats_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > lons_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timeunits_;
    bool time_noleap_;
    int32_t firsttimevalue_;
    int32_t timehourinterval_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TCsP_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TCsP_IndexPair

// int32 latIndex = 1;
inline void TCsP_IndexPair::clear_latindex() {
  _impl_.latindex_ = 0;
}
inline int32_t TCsP_IndexPair::_internal_latindex() const {
  return _impl_.latindex_;
}
inline int32_t TCsP_IndexPair::latindex() const {
  // @@protoc_insertion_point(field_get:TCsP.IndexPair.latIndex)
  return _internal_latindex();
}
inline void TCsP_IndexPair::_internal_set_latindex(int32_t value) {
  
  _impl_.latindex_ = value;
}
inline void TCsP_IndexPair::set_latindex(int32_t value) {
  _internal_set_latindex(value);
  // @@protoc_insertion_point(field_set:TCsP.IndexPair.latIndex)
}

// int32 lonIndex = 2;
inline void TCsP_IndexPair::clear_lonindex() {
  _impl_.lonindex_ = 0;
}
inline int32_t TCsP_IndexPair::_internal_lonindex() const {
  return _impl_.lonindex_;
}
inline int32_t TCsP_IndexPair::lonindex() const {
  // @@protoc_insertion_point(field_get:TCsP.IndexPair.lonIndex)
  return _internal_lonindex();
}
inline void TCsP_IndexPair::_internal_set_lonindex(int32_t value) {
  
  _impl_.lonindex_ = value;
}
inline void TCsP_IndexPair::set_lonindex(int32_t value) {
  _internal_set_lonindex(value);
  // @@protoc_insertion_point(field_set:TCsP.IndexPair.lonIndex)
}

// -------------------------------------------------------------------

// TCsP_LatLonPair

// float lat = 1;
inline void TCsP_LatLonPair::clear_lat() {
  _impl_.lat_ = 0;
}
inline float TCsP_LatLonPair::_internal_lat() const {
  return _impl_.lat_;
}
inline float TCsP_LatLonPair::lat() const {
  // @@protoc_insertion_point(field_get:TCsP.LatLonPair.lat)
  return _internal_lat();
}
inline void TCsP_LatLonPair::_internal_set_lat(float value) {
  
  _impl_.lat_ = value;
}
inline void TCsP_LatLonPair::set_lat(float value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:TCsP.LatLonPair.lat)
}

// float lon = 2;
inline void TCsP_LatLonPair::clear_lon() {
  _impl_.lon_ = 0;
}
inline float TCsP_LatLonPair::_internal_lon() const {
  return _impl_.lon_;
}
inline float TCsP_LatLonPair::lon() const {
  // @@protoc_insertion_point(field_get:TCsP.LatLonPair.lon)
  return _internal_lon();
}
inline void TCsP_LatLonPair::_internal_set_lon(float value) {
  
  _impl_.lon_ = value;
}
inline void TCsP_LatLonPair::set_lon(float value) {
  _internal_set_lon(value);
  // @@protoc_insertion_point(field_set:TCsP.LatLonPair.lon)
}

// -------------------------------------------------------------------

// TCsP_VorCellsIndex

// repeated .TCsP.IndexPair vorCellsIndex = 1;
inline int TCsP_VorCellsIndex::_internal_vorcellsindex_size() const {
  return _impl_.vorcellsindex_.size();
}
inline int TCsP_VorCellsIndex::vorcellsindex_size() const {
  return _internal_vorcellsindex_size();
}
inline void TCsP_VorCellsIndex::clear_vorcellsindex() {
  _impl_.vorcellsindex_.Clear();
}
inline ::TCsP_IndexPair* TCsP_VorCellsIndex::mutable_vorcellsindex(int index) {
  // @@protoc_insertion_point(field_mutable:TCsP.VorCellsIndex.vorCellsIndex)
  return _impl_.vorcellsindex_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair >*
TCsP_VorCellsIndex::mutable_vorcellsindex() {
  // @@protoc_insertion_point(field_mutable_list:TCsP.VorCellsIndex.vorCellsIndex)
  return &_impl_.vorcellsindex_;
}
inline const ::TCsP_IndexPair& TCsP_VorCellsIndex::_internal_vorcellsindex(int index) const {
  return _impl_.vorcellsindex_.Get(index);
}
inline const ::TCsP_IndexPair& TCsP_VorCellsIndex::vorcellsindex(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.VorCellsIndex.vorCellsIndex)
  return _internal_vorcellsindex(index);
}
inline ::TCsP_IndexPair* TCsP_VorCellsIndex::_internal_add_vorcellsindex() {
  return _impl_.vorcellsindex_.Add();
}
inline ::TCsP_IndexPair* TCsP_VorCellsIndex::add_vorcellsindex() {
  ::TCsP_IndexPair* _add = _internal_add_vorcellsindex();
  // @@protoc_insertion_point(field_add:TCsP.VorCellsIndex.vorCellsIndex)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair >&
TCsP_VorCellsIndex::vorcellsindex() const {
  // @@protoc_insertion_point(field_list:TCsP.VorCellsIndex.vorCellsIndex)
  return _impl_.vorcellsindex_;
}

// -------------------------------------------------------------------

// TCsP_Typhoon

// repeated .TCsP.IndexPair maxVorCells = 1;
inline int TCsP_Typhoon::_internal_maxvorcells_size() const {
  return _impl_.maxvorcells_.size();
}
inline int TCsP_Typhoon::maxvorcells_size() const {
  return _internal_maxvorcells_size();
}
inline void TCsP_Typhoon::clear_maxvorcells() {
  _impl_.maxvorcells_.Clear();
}
inline ::TCsP_IndexPair* TCsP_Typhoon::mutable_maxvorcells(int index) {
  // @@protoc_insertion_point(field_mutable:TCsP.Typhoon.maxVorCells)
  return _impl_.maxvorcells_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair >*
TCsP_Typhoon::mutable_maxvorcells() {
  // @@protoc_insertion_point(field_mutable_list:TCsP.Typhoon.maxVorCells)
  return &_impl_.maxvorcells_;
}
inline const ::TCsP_IndexPair& TCsP_Typhoon::_internal_maxvorcells(int index) const {
  return _impl_.maxvorcells_.Get(index);
}
inline const ::TCsP_IndexPair& TCsP_Typhoon::maxvorcells(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.maxVorCells)
  return _internal_maxvorcells(index);
}
inline ::TCsP_IndexPair* TCsP_Typhoon::_internal_add_maxvorcells() {
  return _impl_.maxvorcells_.Add();
}
inline ::TCsP_IndexPair* TCsP_Typhoon::add_maxvorcells() {
  ::TCsP_IndexPair* _add = _internal_add_maxvorcells();
  // @@protoc_insertion_point(field_add:TCsP.Typhoon.maxVorCells)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_IndexPair >&
TCsP_Typhoon::maxvorcells() const {
  // @@protoc_insertion_point(field_list:TCsP.Typhoon.maxVorCells)
  return _impl_.maxvorcells_;
}

// repeated .TCsP.LatLonPair geoCenters = 2;
inline int TCsP_Typhoon::_internal_geocenters_size() const {
  return _impl_.geocenters_.size();
}
inline int TCsP_Typhoon::geocenters_size() const {
  return _internal_geocenters_size();
}
inline void TCsP_Typhoon::clear_geocenters() {
  _impl_.geocenters_.Clear();
}
inline ::TCsP_LatLonPair* TCsP_Typhoon::mutable_geocenters(int index) {
  // @@protoc_insertion_point(field_mutable:TCsP.Typhoon.geoCenters)
  return _impl_.geocenters_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_LatLonPair >*
TCsP_Typhoon::mutable_geocenters() {
  // @@protoc_insertion_point(field_mutable_list:TCsP.Typhoon.geoCenters)
  return &_impl_.geocenters_;
}
inline const ::TCsP_LatLonPair& TCsP_Typhoon::_internal_geocenters(int index) const {
  return _impl_.geocenters_.Get(index);
}
inline const ::TCsP_LatLonPair& TCsP_Typhoon::geocenters(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.geoCenters)
  return _internal_geocenters(index);
}
inline ::TCsP_LatLonPair* TCsP_Typhoon::_internal_add_geocenters() {
  return _impl_.geocenters_.Add();
}
inline ::TCsP_LatLonPair* TCsP_Typhoon::add_geocenters() {
  ::TCsP_LatLonPair* _add = _internal_add_geocenters();
  // @@protoc_insertion_point(field_add:TCsP.Typhoon.geoCenters)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_LatLonPair >&
TCsP_Typhoon::geocenters() const {
  // @@protoc_insertion_point(field_list:TCsP.Typhoon.geoCenters)
  return _impl_.geocenters_;
}

// int32 startTimeIndex = 3;
inline void TCsP_Typhoon::clear_starttimeindex() {
  _impl_.starttimeindex_ = 0;
}
inline int32_t TCsP_Typhoon::_internal_starttimeindex() const {
  return _impl_.starttimeindex_;
}
inline int32_t TCsP_Typhoon::starttimeindex() const {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.startTimeIndex)
  return _internal_starttimeindex();
}
inline void TCsP_Typhoon::_internal_set_starttimeindex(int32_t value) {
  
  _impl_.starttimeindex_ = value;
}
inline void TCsP_Typhoon::set_starttimeindex(int32_t value) {
  _internal_set_starttimeindex(value);
  // @@protoc_insertion_point(field_set:TCsP.Typhoon.startTimeIndex)
}

// int32 endTimeIndex = 4;
inline void TCsP_Typhoon::clear_endtimeindex() {
  _impl_.endtimeindex_ = 0;
}
inline int32_t TCsP_Typhoon::_internal_endtimeindex() const {
  return _impl_.endtimeindex_;
}
inline int32_t TCsP_Typhoon::endtimeindex() const {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.endTimeIndex)
  return _internal_endtimeindex();
}
inline void TCsP_Typhoon::_internal_set_endtimeindex(int32_t value) {
  
  _impl_.endtimeindex_ = value;
}
inline void TCsP_Typhoon::set_endtimeindex(int32_t value) {
  _internal_set_endtimeindex(value);
  // @@protoc_insertion_point(field_set:TCsP.Typhoon.endTimeIndex)
}

// repeated .TCsP.VorCellsIndex vorsCellsIndex = 5;
inline int TCsP_Typhoon::_internal_vorscellsindex_size() const {
  return _impl_.vorscellsindex_.size();
}
inline int TCsP_Typhoon::vorscellsindex_size() const {
  return _internal_vorscellsindex_size();
}
inline void TCsP_Typhoon::clear_vorscellsindex() {
  _impl_.vorscellsindex_.Clear();
}
inline ::TCsP_VorCellsIndex* TCsP_Typhoon::mutable_vorscellsindex(int index) {
  // @@protoc_insertion_point(field_mutable:TCsP.Typhoon.vorsCellsIndex)
  return _impl_.vorscellsindex_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_VorCellsIndex >*
TCsP_Typhoon::mutable_vorscellsindex() {
  // @@protoc_insertion_point(field_mutable_list:TCsP.Typhoon.vorsCellsIndex)
  return &_impl_.vorscellsindex_;
}
inline const ::TCsP_VorCellsIndex& TCsP_Typhoon::_internal_vorscellsindex(int index) const {
  return _impl_.vorscellsindex_.Get(index);
}
inline const ::TCsP_VorCellsIndex& TCsP_Typhoon::vorscellsindex(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.Typhoon.vorsCellsIndex)
  return _internal_vorscellsindex(index);
}
inline ::TCsP_VorCellsIndex* TCsP_Typhoon::_internal_add_vorscellsindex() {
  return _impl_.vorscellsindex_.Add();
}
inline ::TCsP_VorCellsIndex* TCsP_Typhoon::add_vorscellsindex() {
  ::TCsP_VorCellsIndex* _add = _internal_add_vorscellsindex();
  // @@protoc_insertion_point(field_add:TCsP.Typhoon.vorsCellsIndex)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_VorCellsIndex >&
TCsP_Typhoon::vorscellsindex() const {
  // @@protoc_insertion_point(field_list:TCsP.Typhoon.vorsCellsIndex)
  return _impl_.vorscellsindex_;
}

// -------------------------------------------------------------------

// TCsP

// repeated .TCsP.Typhoon typhoons = 1;
inline int TCsP::_internal_typhoons_size() const {
  return _impl_.typhoons_.size();
}
inline int TCsP::typhoons_size() const {
  return _internal_typhoons_size();
}
inline void TCsP::clear_typhoons() {
  _impl_.typhoons_.Clear();
}
inline ::TCsP_Typhoon* TCsP::mutable_typhoons(int index) {
  // @@protoc_insertion_point(field_mutable:TCsP.typhoons)
  return _impl_.typhoons_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_Typhoon >*
TCsP::mutable_typhoons() {
  // @@protoc_insertion_point(field_mutable_list:TCsP.typhoons)
  return &_impl_.typhoons_;
}
inline const ::TCsP_Typhoon& TCsP::_internal_typhoons(int index) const {
  return _impl_.typhoons_.Get(index);
}
inline const ::TCsP_Typhoon& TCsP::typhoons(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.typhoons)
  return _internal_typhoons(index);
}
inline ::TCsP_Typhoon* TCsP::_internal_add_typhoons() {
  return _impl_.typhoons_.Add();
}
inline ::TCsP_Typhoon* TCsP::add_typhoons() {
  ::TCsP_Typhoon* _add = _internal_add_typhoons();
  // @@protoc_insertion_point(field_add:TCsP.typhoons)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TCsP_Typhoon >&
TCsP::typhoons() const {
  // @@protoc_insertion_point(field_list:TCsP.typhoons)
  return _impl_.typhoons_;
}

// string timeUnits = 2;
inline void TCsP::clear_timeunits() {
  _impl_.timeunits_.ClearToEmpty();
}
inline const std::string& TCsP::timeunits() const {
  // @@protoc_insertion_point(field_get:TCsP.timeUnits)
  return _internal_timeunits();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TCsP::set_timeunits(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timeunits_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TCsP.timeUnits)
}
inline std::string* TCsP::mutable_timeunits() {
  std::string* _s = _internal_mutable_timeunits();
  // @@protoc_insertion_point(field_mutable:TCsP.timeUnits)
  return _s;
}
inline const std::string& TCsP::_internal_timeunits() const {
  return _impl_.timeunits_.Get();
}
inline void TCsP::_internal_set_timeunits(const std::string& value) {
  
  _impl_.timeunits_.Set(value, GetArenaForAllocation());
}
inline std::string* TCsP::_internal_mutable_timeunits() {
  
  return _impl_.timeunits_.Mutable(GetArenaForAllocation());
}
inline std::string* TCsP::release_timeunits() {
  // @@protoc_insertion_point(field_release:TCsP.timeUnits)
  return _impl_.timeunits_.Release();
}
inline void TCsP::set_allocated_timeunits(std::string* timeunits) {
  if (timeunits != nullptr) {
    
  } else {
    
  }
  _impl_.timeunits_.SetAllocated(timeunits, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timeunits_.IsDefault()) {
    _impl_.timeunits_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TCsP.timeUnits)
}

// bool time_noleap = 3;
inline void TCsP::clear_time_noleap() {
  _impl_.time_noleap_ = false;
}
inline bool TCsP::_internal_time_noleap() const {
  return _impl_.time_noleap_;
}
inline bool TCsP::time_noleap() const {
  // @@protoc_insertion_point(field_get:TCsP.time_noleap)
  return _internal_time_noleap();
}
inline void TCsP::_internal_set_time_noleap(bool value) {
  
  _impl_.time_noleap_ = value;
}
inline void TCsP::set_time_noleap(bool value) {
  _internal_set_time_noleap(value);
  // @@protoc_insertion_point(field_set:TCsP.time_noleap)
}

// int32 firstTimeValue = 4;
inline void TCsP::clear_firsttimevalue() {
  _impl_.firsttimevalue_ = 0;
}
inline int32_t TCsP::_internal_firsttimevalue() const {
  return _impl_.firsttimevalue_;
}
inline int32_t TCsP::firsttimevalue() const {
  // @@protoc_insertion_point(field_get:TCsP.firstTimeValue)
  return _internal_firsttimevalue();
}
inline void TCsP::_internal_set_firsttimevalue(int32_t value) {
  
  _impl_.firsttimevalue_ = value;
}
inline void TCsP::set_firsttimevalue(int32_t value) {
  _internal_set_firsttimevalue(value);
  // @@protoc_insertion_point(field_set:TCsP.firstTimeValue)
}

// int32 timeHourInterval = 5;
inline void TCsP::clear_timehourinterval() {
  _impl_.timehourinterval_ = 0;
}
inline int32_t TCsP::_internal_timehourinterval() const {
  return _impl_.timehourinterval_;
}
inline int32_t TCsP::timehourinterval() const {
  // @@protoc_insertion_point(field_get:TCsP.timeHourInterval)
  return _internal_timehourinterval();
}
inline void TCsP::_internal_set_timehourinterval(int32_t value) {
  
  _impl_.timehourinterval_ = value;
}
inline void TCsP::set_timehourinterval(int32_t value) {
  _internal_set_timehourinterval(value);
  // @@protoc_insertion_point(field_set:TCsP.timeHourInterval)
}

// repeated float lats = 6;
inline int TCsP::_internal_lats_size() const {
  return _impl_.lats_.size();
}
inline int TCsP::lats_size() const {
  return _internal_lats_size();
}
inline void TCsP::clear_lats() {
  _impl_.lats_.Clear();
}
inline float TCsP::_internal_lats(int index) const {
  return _impl_.lats_.Get(index);
}
inline float TCsP::lats(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.lats)
  return _internal_lats(index);
}
inline void TCsP::set_lats(int index, float value) {
  _impl_.lats_.Set(index, value);
  // @@protoc_insertion_point(field_set:TCsP.lats)
}
inline void TCsP::_internal_add_lats(float value) {
  _impl_.lats_.Add(value);
}
inline void TCsP::add_lats(float value) {
  _internal_add_lats(value);
  // @@protoc_insertion_point(field_add:TCsP.lats)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
TCsP::_internal_lats() const {
  return _impl_.lats_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
TCsP::lats() const {
  // @@protoc_insertion_point(field_list:TCsP.lats)
  return _internal_lats();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
TCsP::_internal_mutable_lats() {
  return &_impl_.lats_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
TCsP::mutable_lats() {
  // @@protoc_insertion_point(field_mutable_list:TCsP.lats)
  return _internal_mutable_lats();
}

// repeated float lons = 7;
inline int TCsP::_internal_lons_size() const {
  return _impl_.lons_.size();
}
inline int TCsP::lons_size() const {
  return _internal_lons_size();
}
inline void TCsP::clear_lons() {
  _impl_.lons_.Clear();
}
inline float TCsP::_internal_lons(int index) const {
  return _impl_.lons_.Get(index);
}
inline float TCsP::lons(int index) const {
  // @@protoc_insertion_point(field_get:TCsP.lons)
  return _internal_lons(index);
}
inline void TCsP::set_lons(int index, float value) {
  _impl_.lons_.Set(index, value);
  // @@protoc_insertion_point(field_set:TCsP.lons)
}
inline void TCsP::_internal_add_lons(float value) {
  _impl_.lons_.Add(value);
}
inline void TCsP::add_lons(float value) {
  _internal_add_lons(value);
  // @@protoc_insertion_point(field_add:TCsP.lons)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
TCsP::_internal_lons() const {
  return _impl_.lons_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
TCsP::lons() const {
  // @@protoc_insertion_point(field_list:TCsP.lons)
  return _internal_lons();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
TCsP::_internal_mutable_lons() {
  return &_impl_.lons_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
TCsP::mutable_lons() {
  // @@protoc_insertion_point(field_mutable_list:TCsP.lons)
  return _internal_mutable_lons();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TCsP_2eproto
