//
//  VortexesDumper.cpp
//  TC_Tracker_CLI
//
//  Created by the-1000th-summer on 2021/10/15.
//


#include <netcdf>
#include "multiArray.h"
#include "VortexesDumper.h"

namespace TTCore {

VortexesDumper::VortexesDumper(const std::string vorNcFilePath, const std::string &oFilePath, TCInfo &tcInfo) : vorNcFilePath(vorNcFilePath), oFilePath(oFilePath), tcInfo(tcInfo) {
    
}

void VortexesDumper::setLatLonData(float *latArr, size_t latDimLen, float *lonArr, size_t lonDimLen) {
    latData = std::make_unique<float[]>(latDimLen);
    lonData = std::make_unique<float[]>(lonDimLen);
    std::copy(latArr, latArr+latDimLen, latData.get());
    std::copy(lonArr, lonArr+lonDimLen, lonData.get());
    this->latDimLen = latDimLen;
    this->lonDimLen = lonDimLen;
    latLonDataDone = true;
}

void VortexesDumper::dumpVortexes2NC(const std::vector<std::vector<std::unordered_set<std::pair<int, int>, pair_hash>>> &allVorsCellsIndex) {
    assert(latLonDataDone);
    
    netCDF::NcFile oFile(oFilePath, netCDF::NcFile::replace);
    
    auto timeDimLen = allVorsCellsIndex.size();
    // dimensions
    auto timeDim = oFile.addDim("time");
    auto latDim = oFile.addDim("lat", latDimLen);
    auto lonDim = oFile.addDim("lon", lonDimLen);
    // variables
    auto timeVar = oFile.addVar("time", netCDF::NcType::nc_INT, timeDim);
    auto latVar = oFile.addVar("lat", netCDF::NcType::nc_FLOAT, latDim);
    auto lonVar = oFile.addVar("lon", netCDF::NcType::nc_FLOAT, lonDim);
    auto vorVar = oFile.addVar("Vorticity", netCDF::NcType::nc_FLOAT, {timeDim, latDim, lonDim});
    // data
    auto timeData = std::make_unique<float[]>(timeDimLen);
    auto vorData = ThreeDArray(timeDimLen, latDimLen, lonDimLen);
    fillTimeData(timeData.get(), timeDimLen);
    fillVorData(allVorsCellsIndex, vorData);
    
    // attrs
    netCDF::NcFile vorFile(vorNcFilePath, netCDF::NcFile::read);
    copyAllCharAtt(vorFile.getVar("time"), timeVar);
    copyAllCharAtt(vorFile.getVar("lat"), latVar);
    copyAllCharAtt(vorFile.getVar("lon"), lonVar);
    vorVar.putAtt("units", "s^-1");
    vorVar.putAtt("_FillValue", netCDF::NcType::nc_FLOAT, 0.0);
    
    // compression
    vorVar.setCompression(true, true, 2);
    
    timeVar.putVar({0}, {timeDimLen}, timeData.get());
    latVar.putVar(latData.get());
    lonVar.putVar(lonData.get());
    vorVar.putVar(vorData.get());
    
    // global attrs
    UtilFunc::appendHistoryInfo(oFile, "generated by VortexesDumper");
    
    oFile.close();
}

void VortexesDumper::fillTimeData(float *timeData, size_t dataLen) {
    int startTI = tcInfo.getFirstTValue();
    const int hourInterval = tcInfo.getHourInterval();
    std::generate(timeData, timeData+dataLen, [&startTI, hourInterval]{ return startTI+=hourInterval; });
}

void VortexesDumper::fillVorData(const std::vector<std::vector<std::unordered_set<std::pair<int, int>, pair_hash>>> &allVorsCellsIndex, ThreeDArray &vorData) {
    const auto timeDimLen = allVorsCellsIndex.size();
    auto originVorData = ThreeDArray(timeDimLen, latDimLen, lonDimLen);
    netCDF::NcFile vorFile(vorNcFilePath, netCDF::NcFile::read);
    vorFile.getVar("Vorticity").getVar(originVorData.get());
    vorFile.close();
    
    for (int i = 0; i < timeDimLen; ++i) {
        if (allVorsCellsIndex[i].empty()) { continue; }
        for (auto const &oneVortexCellsIndex : allVorsCellsIndex[i]) {
            for (auto const &cellIndex : oneVortexCellsIndex) {
                vorData(i, cellIndex.first, cellIndex.second) = originVorData(i, cellIndex.first, cellIndex.second);
            }
        }
    }
}

void VortexesDumper::copyAllCharAtt(const netCDF::NcVar &inVar, netCDF::NcVar &oVar) {
    auto inVarAtts = inVar.getAtts();
    for (auto const &inVarAtt : inVarAtts) {
        if (inVarAtt.second.getType() == netCDF::NcType::nc_CHAR) {
            std::string attValue;
            inVarAtt.second.getValues(attValue);
            oVar.putAtt(inVarAtt.first, attValue);
        }
    }
}

}
