//
//  VortexesDumper.cpp
//  TC_Tracker_CLI
//
//  Created by the-1000th-summer on 2021/10/15.
//

#include <fstream>
#include <netcdf>
#include "multiArray.h"
#include "Utils.h"
#include "VortexesDumper.h"
#ifdef GETVORBASEDONREAL
  #include "vortexes.pb.h"
#endif
namespace TTCore {

VortexesDumper::VortexesDumper(const std::string vorNcFilePath, const std::string &oFilePath, const TCInfo &tcInfo) : vorNcFilePath(vorNcFilePath), oFilePath(oFilePath), tcInfo(tcInfo) {
    
}

/// 将纬度经度数据写到该对象对应的属性里
/// @param[in] latArr 纬度数据
/// @param[in] latDimLen latArr长度
/// @param[in] lonArr 经度数据
/// @param[in] lonDimLen lonArr长度
void VortexesDumper::setLatLonData(const float* const latArr, size_t latDimLen, const float* const lonArr, size_t lonDimLen) {
    latData = std::make_unique<float[]>(latDimLen);
    lonData = std::make_unique<float[]>(lonDimLen);
    std::copy(latArr, latArr+latDimLen, latData.get());
    std::copy(lonArr, lonArr+lonDimLen, lonData.get());
    this->latDimLen = latDimLen;
    this->lonDimLen = lonDimLen;
    latLonDataDone = true;
}

void VortexesDumper::dumpVortexes2NC(const std::vector<std::vector<std::unordered_set<std::pair<int, int>, pair_hash>>> &allVorsCellsIndex) {
    assert(latLonDataDone);
    
    netCDF::NcFile oFile(oFilePath, netCDF::NcFile::replace);
    
    auto timeDimLen = allVorsCellsIndex.size();
    // dimensions
    auto timeDim = oFile.addDim("time");
    auto latDim = oFile.addDim("lat", latDimLen);
    auto lonDim = oFile.addDim("lon", lonDimLen);
    // variables
    auto timeVar = oFile.addVar("time", netCDF::NcType::nc_INT, timeDim);
    auto latVar = oFile.addVar("lat", netCDF::NcType::nc_FLOAT, latDim);
    auto lonVar = oFile.addVar("lon", netCDF::NcType::nc_FLOAT, lonDim);
    auto vorVar = oFile.addVar("Vorticity", netCDF::NcType::nc_FLOAT, {timeDim, latDim, lonDim});
    // data
    auto timeData = std::make_unique<float[]>(timeDimLen);
    auto vorData = ThreeDArray(timeDimLen, latDimLen, lonDimLen);
    fillTimeData(timeData.get(), timeDimLen);
    fillVorData(allVorsCellsIndex, vorData);
    
    // attrs
    netCDF::NcFile vorFile(vorNcFilePath, netCDF::NcFile::read);
    copyAllCharAtt(vorFile.getVar("time"), timeVar);
    copyAllCharAtt(vorFile.getVar("lat"), latVar);
    copyAllCharAtt(vorFile.getVar("lon"), lonVar);
    vorVar.putAtt("units", "s^-1");
    vorVar.putAtt("_FillValue", netCDF::NcType::nc_FLOAT, 0.0);
    
    // compression
    vorVar.setCompression(true, true, 2);
    
    timeVar.putVar({0}, {timeDimLen}, timeData.get());
    latVar.putVar(latData.get());
    lonVar.putVar(lonData.get());
    vorVar.putVar(vorData.get());
    
    // global attrs
    UtilFunc::appendHistoryInfo(oFile, "generated by VortexesDumper");
    UtilFunc::appendThresholdInfo(oFile);
    
    oFile.close();
}

#ifdef GETVORBASEDONREAL
void VortexesDumper::dumpVortexes2Proto3(const std::vector<std::vector<std::unordered_set<std::pair<int, int>, TTCore::pair_hash>>> &allVorsCellsIndex, const std::vector<std::vector<int>> &findRank) {
    VortexesP v;
    for (int i = 0; i < latDimLen; ++i)
        v.add_lat(latData[i]);
    for (int i = 0; i < lonDimLen; ++i)
        v.add_lon(lonData[i]);
    for (auto const &oneTimeCellsIndex : allVorsCellsIndex) {
        auto vorsAllTime_ptr = v.add_vorsalltime();
        for (auto const &oneVorCellsIndex : oneTimeCellsIndex) {
            auto oneVortex_ptr = vorsAllTime_ptr->add_vorsonetime();
            for (auto const &cellIndex : oneVorCellsIndex) {
                oneVortex_ptr->add_latsindexarr(cellIndex.first);
                oneVortex_ptr->add_lonsindexarr(cellIndex.second);
                oneVortex_ptr->set_isvortex(IsVortex::NOTDECIDED);
            }
        }
    }
    for (auto const &oneTimeRanks : findRank) {
        auto indexAllTime_ptr = v.add_realvorindexesalltime();
        for (const int rank : oneTimeRanks) {
            indexAllTime_ptr->add_realvorindexes1time(rank);
        }
    }
    
    std::fstream output(oFilePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (!v.SerializeToOstream(&output)) {
        std::cout << "Failed to write proto3 file." << std::endl;
        exit(-1);
    }
    
}
#endif

/// 根据tcInfo中的time开始index和interval和time的长度将等差数列数据写入timeData
/// @param[out] timeData 保存时间的数组
/// @param[in] dataLen timeData的长度
void VortexesDumper::fillTimeData(float *timeData, size_t dataLen) {
    const int hourInterval = tcInfo.getHourInterval();
    int startTI = tcInfo.getFirstTValue() - hourInterval;
    std::generate(timeData, timeData+dataLen, [&startTI, hourInterval]{ return startTI+=hourInterval; });
}

/// 根据原始相对涡度数据和vortexes的cells的index提取出仅包含vortex的相对涡度数据的ThreeDArray，并写入vorData
/// @param[in] allVorsCellsIndex 所有时次的vortexes的cells的index
/// @param[out] vorData 待写入的3d array，将包含vortex的相对涡度数据
void VortexesDumper::fillVorData(const std::vector<std::vector<std::unordered_set<std::pair<int, int>, pair_hash>>> &allVorsCellsIndex, ThreeDArray &vorData) {
    const auto timeDimLen = allVorsCellsIndex.size();
    auto originVorData = ThreeDArray(timeDimLen, latDimLen, lonDimLen);
    netCDF::NcFile vorFile(vorNcFilePath, netCDF::NcFile::read);
    vorFile.getVar("Vorticity").getVar(originVorData.get());
    vorFile.close();
    
    for (int i = 0; i < timeDimLen; ++i) {
        if (allVorsCellsIndex[i].empty()) { continue; }
        for (auto const &oneVortexCellsIndex : allVorsCellsIndex[i]) {
            for (auto const &cellIndex : oneVortexCellsIndex) {
                vorData(i, cellIndex.first, cellIndex.second) = originVorData(i, cellIndex.first, cellIndex.second);
            }
        }
    }
}

/// 将inVar中所有的CHAR类型的属性拷贝到oVar中
/// @param[in] inVar 被拷贝的变量
/// @param[out] oVar 拷贝到的变量
void VortexesDumper::copyAllCharAtt(const netCDF::NcVar &inVar, netCDF::NcVar &oVar) {
    auto inVarAtts = inVar.getAtts();
    for (auto const &inVarAtt : inVarAtts) {
        if (inVarAtt.second.getType() == netCDF::NcType::nc_CHAR) {
            std::string attValue;
            inVarAtt.second.getValues(attValue);
            oVar.putAtt(inVarAtt.first, attValue);
        }
    }
}

}
